# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from pydantic import TypeAdapter
from pyrpckit.client import RpcClientCore

from showcase.client.metadata import CALCULATOR_ADD, CALCULATOR_DIVIDE
from showcase.client.models import BinaryOperationParams, CalculationResult

_CALCULATOR_ADD_RESULT_ADAPTER = TypeAdapter(CalculationResult)

_CALCULATOR_DIVIDE_RESULT_ADAPTER = TypeAdapter(CalculationResult)


class CalculatorApi:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def add(
        self,
        *,
        left: float,
        right: float,
        decimal_places: int | None = None,
    ) -> CalculationResult:
        values: dict[str, object] = {}
        values["left"] = left
        values["right"] = right
        values["decimalPlaces"] = decimal_places
        params = BinaryOperationParams.model_validate(values)
        return await self._rpc.request(
            CALCULATOR_ADD,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
            result_adapter=_CALCULATOR_ADD_RESULT_ADAPTER,
        )

    async def divide(
        self,
        *,
        left: float,
        right: float,
        decimal_places: int | None = None,
    ) -> CalculationResult:
        values: dict[str, object] = {}
        values["left"] = left
        values["right"] = right
        values["decimalPlaces"] = decimal_places
        params = BinaryOperationParams.model_validate(values)
        return await self._rpc.request(
            CALCULATOR_DIVIDE,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
            result_adapter=_CALCULATOR_DIVIDE_RESULT_ADAPTER,
        )
