# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from examples.calculator_client.namespaces.calculator import CalculatorNamespaceClient

__all__ = [
    "CalculatorNamespaceClient",
]
