# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from pyrpckit.client import RpcTransport

from examples.calculator_client.models import (
    BinaryOperationParams,
    CalculationResult,
    RpcMethod,
)


class CalculatorNamespaceClient:
    def __init__(self, transport: RpcTransport) -> None:
        self._transport = transport

    async def add(
        self,
        *,
        left: float,
        right: float,
    ) -> CalculationResult:
        """Add two numbers."""
        params = BinaryOperationParams(
            left=left,
            right=right,
        )
        result = await self._transport.request(
            RpcMethod.CALCULATOR_ADD,
            params.model_dump(mode="json", exclude_none=True),
        )
        return CalculationResult.model_validate(result)

    async def divide(
        self,
        *,
        left: float,
        right: float,
    ) -> CalculationResult:
        """Divide the left number by the right number."""
        params = BinaryOperationParams(
            left=left,
            right=right,
        )
        result = await self._transport.request(
            RpcMethod.CALCULATOR_DIVIDE,
            params.model_dump(mode="json", exclude_none=True),
        )
        return CalculationResult.model_validate(result)
