from pathlib import Path
from typing import Any

from pyrpckit.codegen import generate_python_client, render_python_client
from pyrpckit.codegen.python import PythonClientOptions

from .conftest import PACKAGE


def test_the_generated_package_has_one_module_per_concern(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    assert set(files) == {
        "__init__.py",
        "models.py",
        "client.py",
        "namespaces/__init__.py",
        "namespaces/greeting.py",
    }


def test_every_file_names_its_source(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    for content in files.values():
        assert content.startswith(
            "# Generated by pyrpckit from greeting.openrpc.json.\n"
            "# Do not edit this file manually.\n"
        )


def test_operations_become_typed_keyword_only_methods(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    namespace = render_python_client(document, options)["namespaces/greeting.py"]

    assert "    async def say(\n        self,\n        *,\n        name: str,\n" in namespace
    assert "    ) -> SayResult:" in namespace
    assert '        """Greet someone by name."""' in namespace
    assert "        return SayResult.model_validate(result)" in namespace


def test_a_method_without_a_result_returns_none(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    namespace = render_python_client(document, options)["namespaces/greeting.py"]
    forget = namespace.split("    async def forget(", 1)[1]

    assert "    ) -> None:" in forget
    assert "result = await" not in forget


def test_the_result_model_is_imported(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    namespace = render_python_client(document, options)["namespaces/greeting.py"]

    assert (
        f"from {PACKAGE}.models import ForgetParams, RpcMethod, SayParams, SayResult" in namespace
    )


def test_a_namespace_class_never_collides_with_the_client(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    client = render_python_client(document, options)["client.py"]

    assert "class GreetingClient:" in client
    assert "self.greeting = GreetingNamespaceClient(transport)" in client


def test_namespace_class_names_can_be_overridden(document: dict[str, Any]) -> None:
    options = PythonClientOptions(
        package=PACKAGE,
        namespace_class_names={"greeting": "Greetings"},
    )

    client = render_python_client(document, options)["client.py"]

    assert "self.greeting = Greetings(transport)" in client


def test_the_notification_stream_is_typed(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    client = render_python_client(document, options)["client.py"]

    assert (
        "    async def notifications(self) -> AsyncIterator[GreetingChangedNotification]:" in client
    )


def test_writing_reports_changed_files_and_is_idempotent(
    document: dict[str, Any],
    options: PythonClientOptions,
    tmp_path: Path,
) -> None:
    output = tmp_path / PACKAGE

    written = generate_python_client(document, output, options)
    assert len(written) == 5
    assert (output / "namespaces" / "greeting.py").exists()

    assert generate_python_client(document, output, options) == ()


def test_check_reports_without_writing(
    document: dict[str, Any],
    options: PythonClientOptions,
    tmp_path: Path,
) -> None:
    output = tmp_path / PACKAGE

    outdated = generate_python_client(document, output, options, check=True)

    assert len(outdated) == 5
    assert not output.exists()
