import shutil
import subprocess
from copy import deepcopy
from pathlib import Path
from textwrap import dedent
from typing import Any

import pytest

from rpckit import RpcChannel, RpcService
from rpckit.codegen import generate_typescript_client, render_typescript_client
from rpckit.codegen.typescript import TypeScriptClientOptions
from rpckit.codegen.writer import MANIFEST


def options() -> TypeScriptClientOptions:
    return TypeScriptClientOptions(
        client_name="GreetingClient",
        source="greeting.openrpc.json",
    )


def test_the_generated_package_has_one_module_per_concern(
    document: dict[str, Any],
) -> None:
    files = render_typescript_client(document, options())

    assert set(files) == {
        MANIFEST,
        "core.ts",
        "namespaces/greeting.ts",
        "namespaces/index.ts",
        "client.ts",
        "errors.ts",
        "index.ts",
        "routes.ts",
        "models.ts",
    }
    assert all(
        content.startswith(
            "// Generated by rpckit from greeting.openrpc.json.\n"
            "// Do not edit this file manually.\n"
            "// Regenerate it from the OpenRPC document instead.\n"
        )
        for name, content in files.items()
        if name != MANIFEST
    )


def test_renders_typed_api_groups_and_notifications(document: dict[str, Any]) -> None:
    files = render_typescript_client(document, options())
    api = files["namespaces/greeting.ts"]
    client = files["client.ts"]

    assert "export class Greeting {" in api
    assert "say(params: SayParams): Promise<SayResult>" in api
    assert "async forget(params: ForgetParams): Promise<void>" in api
    assert "greeted(): Promise<GreetedResult>" in api
    assert "readonly greeting: Greeting;" in client
    assert "changed(): AsyncIterable<GreetingUpdate>" in api
    assert "events()" not in client


def test_renders_models_as_types_and_literal_unions(
    document: dict[str, Any],
) -> None:
    document_with_enum = deepcopy(document)
    inline_enum = document_with_enum["components"]["schemas"]["SayParams"][
        "properties"
    ]["name"]
    inline_enum["enum"] = ["Ada", "Grace"]

    models = render_typescript_client(document_with_enum, options())["models.ts"]

    assert 'name: "Ada" | "Grace";' in models
    assert "export type GreetingUpdate = GreetingSaid | GreetingForgotten;" in models
    assert 'type: "greeting.said";' in models


def test_route_definitions_keep_wire_names(
    document: dict[str, Any],
) -> None:
    routes = render_typescript_client(document, options())["routes.ts"]

    assert 'method: "greeting.forget"' in routes
    assert "greetingForget: defineRoute<ForgetParams, null>" in routes
    assert "greetingGreeted: defineRoute<undefined, GreetedResult>" in routes
    assert "greetingChanged: defineNotification<GreetingUpdate>" in routes


def test_api_calls_infer_their_types_from_route_metadata(
    document: dict[str, Any],
) -> None:
    files = render_typescript_client(document, options())
    api = files["namespaces/greeting.ts"]

    assert ".request<SayResult>" not in api
    assert ".notifications<GreetingUpdate>" not in api
    assert "this.rpc.request(routes.greetingSay, params)" in api
    assert "this.rpc.notifications(notifications.greetingChanged)" in api


def test_stably_named_remote_errors_get_their_own_module(
    document: dict[str, Any],
) -> None:
    errors = render_typescript_client(document, options())["errors.ts"]

    assert "class UnknownGreetingError extends RpcRemoteError" in errors
    assert 'static readonly code = "unknown_greeting"' in errors


def test_transport_module_can_be_configured(document: dict[str, Any]) -> None:
    configured = TypeScriptClientOptions(transport_module="@example/rpc")

    files = render_typescript_client(document, configured)

    assert 'import type { RpcTransport } from "@example/rpc";' in files["core.ts"]


def test_api_root_and_names_are_shared_with_the_python_layout(
    document: dict[str, Any],
) -> None:
    nested = deepcopy(document)
    nested["methods"][0]["name"] = "browser.nav.navigate"
    nested["methods"] = [nested["methods"][0]]
    configured = TypeScriptClientOptions(
        client_name="BrowserControlClient",
        api_root="browser",
        api_names={"nav": "navigation"},
    )

    files = render_typescript_client(nested, configured)

    assert "namespaces/navigation.ts" in files
    assert "export class Navigation" in files["namespaces/navigation.ts"]
    assert "readonly navigation: Navigation;" in files["client.ts"]
    assert 'method: "browser.nav.navigate"' in files["routes.ts"]


def test_all_optional_params_default_to_an_empty_object(
    document: dict[str, Any],
) -> None:
    optional = deepcopy(document)
    optional["methods"][0]["params"][0]["required"] = False
    optional["components"]["schemas"]["SayParams"]["required"] = []

    api = render_typescript_client(optional, options())["namespaces/greeting.ts"]

    assert "say(params: SayParams = {}): Promise<SayResult>" in api


def test_camel_case_wire_fields_stay_camel_case_in_typescript(
    document: dict[str, Any],
) -> None:
    camel_document = deepcopy(document)
    params = camel_document["components"]["schemas"]["SayParams"]
    params["properties"]["projectId"] = params["properties"].pop("name")
    params["required"] = ["projectId"]

    models = render_typescript_client(camel_document, options())["models.ts"]

    assert "projectId: string;" in models


def test_servers_generate_endpoint_metadata(document: dict[str, Any]) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "greeting-api",
            "url": "wss://{host}/{projectId}",
            "variables": {
                "host": {"default": "api.example.com"},
                "projectId": {"default": "demo"},
            },
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]

    files = render_typescript_client(deployed, options())

    assert "endpoints.ts" in files
    assert "greetingApi: {" in files["endpoints.ts"]
    assert "function greetingApi(" in files["endpoints.ts"]
    assert 'type: "websocket"' in files["endpoints.ts"]
    assert 'from "./endpoints"' in files["index.ts"]


def test_single_server_websocket_clients_accept_compact_url_overrides(
    document: dict[str, Any],
) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "greeting-api",
            "url": "wss://api.example.com/greeting",
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
                "subprotocols": ["jsonrpc"],
            },
        }
    ]
    configured = TypeScriptClientOptions(with_transport="websocket")

    files = render_typescript_client(deployed, configured)

    assert "readonly url?: string | URL;" in files["client.ts"]
    assert 'overrides["greeting-api"] ??= options.url;' in files["client.ts"]
    assert "readonly subprotocols?: readonly string[];" in files["endpoints.ts"]
    assert (
        "subprotocols: override.subprotocols ?? declared.subprotocols,"
        in files["endpoints.ts"]
    )
    assert "url: string | URL" in files["transport.ts"]


def test_binary_streams_generate_typed_media_clients(document: dict[str, Any]) -> None:
    deployed = deepcopy(document)
    deployed["x-rpckit-binary-streams"] = [
        {
            "name": "voice",
            "url": "wss://media/{sessionId}",
            "direction": "server-to-client",
            "contentType": "audio/pcm;rate=24000",
            "frameType": "binary",
            "variables": {"sessionId": {"default": "demo"}},
            "subprotocols": ["voice.v1"],
        }
    ]
    deployed["servers"] = [
        {
            "name": "control",
            "url": "wss://api/rpc",
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]
    configured = TypeScriptClientOptions(with_transport="websocket")

    files = render_typescript_client(deployed, configured)
    media = files["streams.ts"]
    client = files["client.ts"]

    assert "class BinaryWebSocketStream" in media
    assert "send(frame: ArrayBuffer | ArrayBufferView)" not in media
    assert 'socket.binaryType = "arraybuffer"' in media
    assert "this.#socket.send(frame);" in media
    assert media.count("JSON.stringify") == 1
    assert "JSON.stringify(end)" in media
    assert "base64" not in media.lower()
    assert "voice(" in client
    assert client.count("readonly sessionId?: string") == 1
    assert 'contentType: "audio/pcm;rate=24000"' in media
    assert 'from "./streams"' in files["index.ts"]


def test_the_index_exports_everything_a_caller_needs(
    document: dict[str, Any],
) -> None:
    index = render_typescript_client(document, options())["index.ts"]

    assert 'export { GreetingClient } from "./client";' in index
    assert 'export type * from "./models";' in index
    assert 'export * from "./namespaces";' in index
    assert 'export * from "./errors";' in index
    assert 'export { routes, notifications } from "./routes";' in index
    assert 'export { RpcConnectionClosed, RpcRemoteError } from "./core";' in index
    assert "export type {" in index
    assert "  RpcClientCore," in index


def test_writing_is_idempotent_and_check_does_not_write(
    document: dict[str, Any],
    tmp_path: Path,
) -> None:
    output = tmp_path / "generated"

    assert len(generate_typescript_client(document, output, options())) == 9
    assert generate_typescript_client(document, output, options()) == ()
    (output / "client.ts").write_text("stale\n", encoding="utf-8")

    assert generate_typescript_client(document, output, options(), check=True) == (
        output / "client.ts",
    )
    assert (output / "client.ts").read_text(encoding="utf-8") == "stale\n"


def test_generated_typescript_is_prettier_formatted(
    document: dict[str, Any],
    tmp_path: Path,
) -> None:
    output = tmp_path / "generated"
    nested = deepcopy(document)
    first = nested["methods"][0]
    second = deepcopy(first)
    first["name"] = "tasks.list"
    second["name"] = "tasks.status.set"
    nested["methods"] = [first, second]
    nested["x-rpckit-binary-streams"] = [
        {
            "name": "voice",
            "url": "wss://media",
            "direction": "server-to-client",
            "frameType": "binary",
        },
        {
            "name": "uploads.audio",
            "url": "wss://media/{sessionId}/upload",
            "direction": "client-to-server",
            "inputContentType": "audio/pcm",
            "frameType": "binary",
            "variables": {"sessionId": {"default": "demo"}},
        },
        {
            "name": "uploads.talk",
            "url": "wss://media/talk",
            "direction": "bidirectional",
            "contentType": "audio/opus",
            "inputContentType": "audio/pcm",
            "frameType": "binary",
        },
    ]
    generate_typescript_client(nested, output, options())
    nested["servers"] = [
        {
            "name": "control",
            "url": "wss://api/rpc",
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]
    configured = TypeScriptClientOptions(
        client_name="GreetingClient",
        source="greeting.openrpc.json",
        with_transport="websocket",
    )
    websocket_media = render_typescript_client(nested, configured)["streams.ts"]
    with (output / "media-websocket.ts").open(
        "w", encoding="utf-8", newline="\n"
    ) as handle:
        handle.write(websocket_media)
    prettier = shutil.which("npx.cmd") or shutil.which("npx")
    if prettier is None:
        pytest.skip("npx is not installed")

    formatting = subprocess.run(
        [prettier, "prettier", "--check", str(output)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert formatting.returncode == 0, formatting.stdout + formatting.stderr


def test_generated_typescript_passes_strict_type_checking(
    document: dict[str, Any],
    tmp_path: Path,
) -> None:
    npx = shutil.which("npx.cmd") or shutil.which("npx")
    if npx is None:
        pytest.skip("npx is not installed")

    output = tmp_path / "generated"
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "primary",
            "url": "wss://{host}/rpc",
            "variables": {"host": {"default": "api.example.com"}},
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]
    deployed["x-rpckit-binary-streams"] = [
        {
            "name": "greeting.frames",
            "url": "wss://{host}/frames",
            "direction": "server-to-client",
            "contentType": "image/jpeg",
            "frameType": "binary",
            "variables": {"host": {"default": "api.example.com"}},
        }
    ]
    generate_typescript_client(
        deployed,
        output,
        TypeScriptClientOptions(
            client_name="GreetingClient",
            source="greeting.openrpc.json",
            with_transport="websocket",
        ),
    )
    consumer = tmp_path / "consumer.ts"
    consumer.write_text(
        dedent(
            """
            import {
              notifications,
              routes,
              type GreetedResult,
              type GreetingUpdate,
              type RpcClientCore,
              type SayResult,
            } from "./generated";

            declare const rpc: RpcClientCore;

            const result: Promise<SayResult> = rpc.request(
              routes.greetingSay,
              { name: "Ada" },
            );
            const greeted: Promise<GreetedResult> = rpc.request(
              routes.greetingGreeted,
            );
            const updates: AsyncIterable<GreetingUpdate> = rpc.notifications(
              notifications.greetingChanged,
            );

            // @ts-expect-error greeting.say requires parameters
            void rpc.request(routes.greetingSay);
            // @ts-expect-error greeting.greeted does not accept parameters
            void rpc.request(routes.greetingGreeted, {});
            // @ts-expect-error name is a string
            void rpc.request(routes.greetingSay, { name: 42 });

            void result;
            void greeted;
            void updates;
            """
        ),
        encoding="utf-8",
        newline="\n",
    )

    type_check = subprocess.run(
        [
            npx,
            "--yes",
            "--package",
            "typescript",
            "tsc",
            "--noEmit",
            "--strict",
            "--target",
            "ES2022",
            "--module",
            "ESNext",
            "--moduleResolution",
            "Bundler",
            "--lib",
            "ES2022,DOM,ESNext.Disposable",
            "--skipLibCheck",
            str(consumer),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert type_check.returncode == 0, type_check.stdout + type_check.stderr


def test_contracts_without_models_do_not_export_a_models_module() -> None:
    channel = RpcChannel("control")

    @channel.server.method
    async def ping() -> str:
        return "pong"

    service = RpcService()
    service.socket("/rpc", channels=[channel])
    document = service.contract(title="Control", base_url="ws://localhost")

    files = render_typescript_client(document.to_openrpc(), options())

    assert "models.ts" not in files
    assert "./models" not in files["index.ts"]
