import shutil
import subprocess
from copy import deepcopy
from pathlib import Path
from typing import Any

import pytest

from pyrpckit.codegen import generate_typescript_client, render_typescript_client
from pyrpckit.codegen.typescript import TypeScriptClientOptions


def options() -> TypeScriptClientOptions:
    return TypeScriptClientOptions(
        client_name="GreetingClient",
        source="greeting.openrpc.json",
    )


def test_the_generated_package_has_one_module_per_concern(
    document: dict[str, Any],
) -> None:
    files = render_typescript_client(document, options())

    assert set(files) == {
        ".pyrpckit-generated.json",
        "core.ts",
        "api/greeting.ts",
        "api/index.ts",
        "client.ts",
        "errors.ts",
        "index.ts",
        "metadata.ts",
        "models.ts",
    }
    assert all(
        content.startswith(
            "// Generated by pyrpckit from greeting.openrpc.json.\n"
            "// Do not edit this file manually.\n"
            "// Regenerate it from the OpenRPC document instead.\n"
        )
        for name, content in files.items()
        if name != ".pyrpckit-generated.json"
    )


def test_renders_typed_api_groups_and_events(document: dict[str, Any]) -> None:
    files = render_typescript_client(document, options())
    api = files["api/greeting.ts"]
    client = files["client.ts"]

    assert "export class GreetingApi {" in api
    assert "say(params: SayParams): Promise<SayResult>" in api
    assert "async forget(params: ForgetParams): Promise<void>" in api
    assert "greeted(): Promise<GreetedResult>" in api
    assert "readonly greeting: GreetingApi;" in client
    assert "events(): AsyncIterable<GreetingEvent>" in client
    assert "notifications()" not in client


def test_renders_models_as_types_and_literal_unions(
    document: dict[str, Any],
) -> None:
    document_with_enum = deepcopy(document)
    inline_enum = document_with_enum["components"]["schemas"]["SayParams"][
        "properties"
    ]["name"]
    inline_enum["enum"] = ["Ada", "Grace"]

    models = render_typescript_client(document_with_enum, options())["models.ts"]

    assert 'name: "Ada" | "Grace";' in models
    assert "export type GreetingEvent = GreetingSaid | GreetingForgotten;" in models
    assert 'type: "greeting.said";' in models


def test_route_metadata_keeps_tags_errors_and_wire_names(
    document: dict[str, Any],
) -> None:
    metadata = render_typescript_client(document, options())["metadata.ts"]

    assert 'method: "greeting.forget"' in metadata
    assert 'tags: ["greeting"]' in metadata
    assert "errorCodes: [-32001]" in metadata
    assert "deprecated: false" in metadata


def test_stably_named_remote_errors_get_their_own_module(
    document: dict[str, Any],
) -> None:
    errors = render_typescript_client(document, options())["errors.ts"]

    assert "class UnknownGreetingError extends RpcRemoteError" in errors
    assert "static readonly code = -32001" in errors


def test_transport_module_can_be_configured(document: dict[str, Any]) -> None:
    configured = TypeScriptClientOptions(transport_module="@example/rpc")

    files = render_typescript_client(document, configured)

    assert 'import type { RpcTransport } from "@example/rpc";' in files["client.ts"]
    assert 'import type { RpcTransport } from "@example/rpc";' in files["core.ts"]


def test_api_root_and_names_are_shared_with_the_python_layout(
    document: dict[str, Any],
) -> None:
    nested = deepcopy(document)
    nested["methods"][0]["name"] = "browser.nav.navigate"
    nested["methods"] = [nested["methods"][0]]
    configured = TypeScriptClientOptions(
        client_name="BrowserControlClient",
        api_root="browser",
        api_names={"nav": "navigation"},
    )

    files = render_typescript_client(nested, configured)

    assert "api/navigation.ts" in files
    assert "export class NavigationApi" in files["api/navigation.ts"]
    assert "readonly navigation: NavigationApi;" in files["client.ts"]
    assert 'method: "browser.nav.navigate"' in files["metadata.ts"]


def test_all_optional_params_default_to_an_empty_object(
    document: dict[str, Any],
) -> None:
    optional = deepcopy(document)
    optional["methods"][0]["params"][0]["required"] = False
    optional["components"]["schemas"]["SayParams"]["required"] = []

    api = render_typescript_client(optional, options())["api/greeting.ts"]

    assert "say(params: SayParams = {}): Promise<SayResult>" in api


def test_camel_case_wire_fields_stay_camel_case_in_typescript(
    document: dict[str, Any],
) -> None:
    camel_document = deepcopy(document)
    params = camel_document["components"]["schemas"]["SayParams"]
    params["properties"]["projectId"] = params["properties"].pop("name")
    params["required"] = ["projectId"]

    models = render_typescript_client(camel_document, options())["models.ts"]

    assert "projectId: string;" in models


def test_servers_generate_endpoint_metadata(document: dict[str, Any]) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "greeting-api",
            "url": "wss://{host}/{projectId}",
            "variables": {
                "host": {"default": "api.example.com"},
                "projectId": {"default": "demo"},
            },
            "x-rpckit-transport": "websocket",
        }
    ]

    files = render_typescript_client(deployed, options())

    assert "endpoints.ts" in files
    assert "greetingApi: defineRpcServer" in files["endpoints.ts"]
    assert "export function greetingApiUrl" in files["endpoints.ts"]
    assert 'transport: "websocket"' in files["endpoints.ts"]
    assert 'from "./endpoints"' in files["index.ts"]


def test_the_index_keeps_a_small_public_surface(document: dict[str, Any]) -> None:
    index = render_typescript_client(document, options())["index.ts"]

    assert 'export { GreetingClient } from "./client";' in index
    assert 'export type { GreetingEvent } from "./models";' in index
    assert "GreetingApi" not in index
    assert "RpcClientCore" not in index


def test_writing_is_idempotent_and_check_does_not_write(
    document: dict[str, Any],
    tmp_path: Path,
) -> None:
    output = tmp_path / "generated"

    assert len(generate_typescript_client(document, output, options())) == 9
    assert generate_typescript_client(document, output, options()) == ()
    (output / "client.ts").write_text("stale\n", encoding="utf-8")

    assert generate_typescript_client(document, output, options(), check=True) == (
        output / "client.ts",
    )
    assert (output / "client.ts").read_text(encoding="utf-8") == "stale\n"


def test_generated_typescript_is_prettier_formatted(
    document: dict[str, Any],
    tmp_path: Path,
) -> None:
    output = tmp_path / "generated"
    generate_typescript_client(document, output, options())
    prettier = shutil.which("npx.cmd") or shutil.which("npx")
    if prettier is None:
        pytest.skip("npx is not installed")

    formatting = subprocess.run(
        [prettier, "prettier", "--check", str(output)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert formatting.returncode == 0, formatting.stdout + formatting.stderr
