import subprocess
import sys
from collections.abc import AsyncIterator, Callable
from copy import deepcopy
from pathlib import Path
from typing import Any

import pytest

import pyrpckit as rpc
from pyrpckit.codegen import generate_python_client, render_python_client
from pyrpckit.codegen.ir import UnsupportedSchemaError
from pyrpckit.codegen.python import PythonClientOptions
from pyrpckit.codegen.writer import MANIFEST

from .conftest import PACKAGE


class _Params(rpc.RpcModel):
    x: int


class _Result(rpc.RpcModel):
    x: int


class _Tick(rpc.RpcModel):
    n: int


class _MissingError(rpc.RpcError):
    pass


def test_the_generated_package_has_one_module_per_concern(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    assert set(files) == {
        MANIFEST,
        "internal/__init__.py",
        "internal/core.py",
        "internal/errors.py",
        "internal/metadata.py",
        "internal/transport.py",
        "internal/unset.py",
        "__init__.py",
        "namespaces/__init__.py",
        "namespaces/greeting.py",
        "client.py",
        "errors.py",
        "routes.py",
        "models.py",
    }


def test_the_generated_package_embeds_its_runtime(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    assert all("from pyrpckit" not in content for content in files.values())
    assert (
        "from greeting_client.internal import RpcClientCore"
        in files["namespaces/greeting.py"]
    )


def test_websocket_lifecycle_stays_out_of_the_public_client(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "production",
            "url": "wss://api.example.com/rpc",
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]
    configured = PythonClientOptions(
        package=options.package,
        client_name=options.client_name,
        source=options.source,
        with_transport="websocket",
    )

    files = render_python_client(deployed, configured)
    client = files["client.py"]

    assert "internal/connection.py" in files
    assert "return ClientConnection(" in client
    assert "eager: bool = True" in client
    assert "async def open(" not in client
    assert "_ConnectionContext" not in client


def test_every_file_names_its_source(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    assert all(
        content.startswith(
            "# Generated by pyrpckit from greeting.openrpc.json.\n"
            "# Do not edit this file manually.\n"
        )
        for name, content in files.items()
        if name != MANIFEST
    )


def test_generated_modules_end_with_one_newline(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    assert all(
        content.endswith("\n") and not content.endswith("\n\n")
        for name, content in files.items()
        if name != MANIFEST
    )


def test_operations_are_typed_methods_on_api_groups(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    api = render_python_client(document, options)["namespaces/greeting.py"]

    assert "class Greeting:" in api
    assert "    async def say(\n        self,\n        *,\n        name: str," in api
    assert "    ) -> SayResult:" in api
    assert '        """Greet someone by name."""' in api
    assert "self._rpc.request(\n            GREETING_SAY," in api


def test_void_and_parameterless_operations_stay_small(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    api = render_python_client(document, options)["namespaces/greeting.py"]
    clear = api.split("    async def clear(", 1)[1]

    assert clear.startswith("self) -> None:")
    assert "params=" not in clear
    assert "await self._rpc.request(" in clear


def test_route_definitions_preserve_the_wire_contract(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    routes = render_python_client(document, options)["routes.py"]

    assert 'method="greeting.say"' in routes
    assert "GREETING_SAY: RpcRouteInfo[SayParams, SayResult]" in routes
    assert "GREETING_GREETED: RpcRouteInfo[None, GreetedResult]" in routes
    assert "result_adapter=TypeAdapter(SayResult)" in routes
    assert 'method="greeting.changed"' in routes


def test_parameter_models_are_serialized_once_in_the_runtime(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    files = render_python_client(document, options)

    api = files["namespaces/greeting.py"]
    runtime = files["internal/core.py"]

    assert "params=params," in api
    assert "params.model_dump" not in api
    serialization = 'params.model_dump(mode="json", by_alias=True, exclude_unset=True)'
    assert serialization in runtime


def test_stably_named_remote_errors_get_their_own_module(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    errors = render_python_client(document, options)["errors.py"]

    assert "class UnknownGreetingError(RpcRemoteError):" in errors
    assert 'code: ClassVar[str] = "unknown_greeting"' in errors


def test_client_name_defaults_to_the_contract_title(document: dict[str, Any]) -> None:
    options = PythonClientOptions(package=PACKAGE)

    client = render_python_client(document, options)["client.py"]

    assert "class GreetingClient:" in client


def test_api_root_and_names_create_a_non_stuttering_tree(
    document: dict[str, Any],
) -> None:
    nested = deepcopy(document)
    nested["methods"][0]["name"] = "browser.nav.navigate"
    nested["methods"] = [nested["methods"][0]]
    options = PythonClientOptions(
        package=PACKAGE,
        client_name="BrowserControlClient",
        api_root="browser",
        api_names={"nav": "navigation"},
    )

    files = render_python_client(nested, options)

    assert "namespaces/navigation.py" in files
    assert "class Navigation:" in files["namespaces/navigation.py"]
    assert "self.navigation = Navigation(self._rpc)" in files["client.py"]
    assert 'method="browser.nav.navigate"' in files["routes.py"]


def test_unknown_api_configuration_is_rejected(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    configured = PythonClientOptions(
        package=options.package,
        api_root="missing",
    )

    with pytest.raises(UnsupportedSchemaError, match="api_root 'missing'"):
        render_python_client(document, configured)


def test_notifications_expose_payloads_in_domain_language(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    api = render_python_client(document, options)["namespaces/greeting.py"]

    assert "def changed(self) -> AsyncIterator[GreetingUpdate]:" in api
    assert "return self._rpc.subscribe(GREETING_CHANGED)" in api


def test_optional_nullable_params_use_unset_instead_of_dropping_none(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    optional = deepcopy(document)
    schema = {"anyOf": [{"type": "string"}, {"type": "null"}]}
    optional["methods"][0]["params"] = [
        {"name": "title", "required": False, "schema": schema}
    ]
    params = optional["components"]["schemas"]["SayParams"]
    params["properties"] = {"title": schema}
    params["required"] = []

    api = render_python_client(optional, options)["namespaces/greeting.py"]

    assert "title: str | None | UnsetType = UNSET" in api
    assert "if title is not UNSET:" in api
    assert 'values["title"] = title' in api
    assert "params=params," in api
    assert "exclude_none" not in api


def test_params_with_a_schema_default_stay_unset_until_the_caller_sets_them(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    defaulted = deepcopy(document)
    schema = {"type": "integer", "default": 80}
    defaulted["methods"][0]["params"] = [
        {"name": "quality", "required": False, "schema": schema}
    ]
    params = defaulted["components"]["schemas"]["SayParams"]
    params["properties"] = {"quality": schema}
    params["required"] = []

    api = render_python_client(defaulted, options)["namespaces/greeting.py"]

    assert "quality: int | UnsetType = UNSET" in api
    assert "quality: int = 80" not in api
    assert "if quality is not UNSET:" in api


def test_camel_case_wire_fields_become_snake_case_python_names(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    camel_document = deepcopy(document)
    params = camel_document["components"]["schemas"]["SayParams"]
    params["properties"]["projectId"] = params["properties"].pop("name")
    params["required"] = ["projectId"]
    say = camel_document["methods"][0]
    say["params"][0]["name"] = "projectId"

    files = render_python_client(camel_document, options)

    assert 'project_id: str = Field(alias="projectId")' in files["models.py"]
    assert "model_config = ConfigDict(validate_by_name=True)" in files["models.py"]
    assert "        project_id: str," in files["namespaces/greeting.py"]
    assert (
        "        params = SayParams(\n            project_id=project_id,"
        in files["namespaces/greeting.py"]
    )
    assert "values:" not in files["namespaces/greeting.py"]


def test_servers_generate_resolvable_endpoint_helpers(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [
        {
            "name": "greeting-api",
            "url": "wss://{host}/{projectId}",
            "variables": {
                "host": {"default": "api.example.com"},
                "projectId": {"default": "demo"},
            },
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]

    files = render_python_client(deployed, options)

    assert "endpoints.py" in files
    assert "class ServerName(StrEnum):" in files["endpoints.py"]
    assert "def greeting_api(" in files["endpoints.py"]
    assert "project_id: str" in files["endpoints.py"]
    assert 'type="websocket"' in files["endpoints.py"]
    assert "ServerName" in files["__init__.py"]


def test_servers_without_variables_do_not_import_variable_metadata(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    deployed = deepcopy(document)
    deployed["servers"] = [{"name": "local", "url": "ws://localhost/rpc"}]

    endpoints = render_python_client(deployed, options)["endpoints.py"]

    assert "RpcServerInfo" in endpoints
    assert "RpcServerVariable" not in endpoints


def test_binary_streams_generate_typed_media_clients(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    deployed = deepcopy(document)
    deployed["x-rpckit-binary-streams"] = [
        {
            "name": "voice",
            "url": "wss://media/{sessionId}",
            "direction": "server-to-client",
            "contentType": "audio/pcm;rate=24000",
            "frameType": "binary",
            "variables": {"sessionId": {"default": "demo"}},
            "subprotocols": ["voice.v1"],
        }
    ]
    deployed["servers"] = [
        {
            "name": "control",
            "url": "wss://api/rpc",
            "x-rpckit-transport": {
                "type": "websocket",
                "messageEncoding": "json",
            },
        }
    ]
    configured = PythonClientOptions(
        package=options.package,
        client_name=options.client_name,
        source=options.source,
        with_transport="websocket",
    )

    files = render_python_client(deployed, configured)
    media = files["streams.py"]

    assert "class BinaryWebSocketStream:" in media
    assert "async def open_binary_stream[" in media
    assert "frame = await self._socket.recv()" in media
    assert "json.dumps" not in media
    assert "base64" not in media.lower()
    assert "def voice(" in files["client.py"]
    assert files["client.py"].count("session_id: str | None = None,") == 1
    assert "self._rpc.variables," in files["client.py"]
    assert "url=url" not in files["client.py"]
    assert 'content_type="audio/pcm;rate=24000"' in media
    assert 'default="demo"' in media
    assert "BinaryWebSocketStream" in files["__init__.py"]


def test_python_name_collisions_fail_with_both_wire_names(
    document: dict[str, Any],
    options: PythonClientOptions,
) -> None:
    collision = deepcopy(document)
    first = collision["methods"][0]
    second = deepcopy(first)
    first["name"] = "greeting.open-tab"
    second["name"] = "greeting.openTab"
    collision["methods"] = [first, second]

    with pytest.raises(UnsupportedSchemaError, match="greeting.open-tab") as error:
        render_python_client(collision, options)

    assert "greeting.openTab" in str(error.value)
    assert "open_tab" in str(error.value)


def test_writing_is_idempotent_and_check_does_not_write(
    document: dict[str, Any],
    options: PythonClientOptions,
    tmp_path: Path,
) -> None:
    output = tmp_path / PACKAGE

    assert len(generate_python_client(document, output, options)) == 14
    assert generate_python_client(document, output, options) == ()
    (output / "client.py").write_text("stale\n", encoding="utf-8")

    assert generate_python_client(document, output, options, check=True) == (
        output / "client.py",
    )
    assert (output / "client.py").read_text(encoding="utf-8") == "stale\n"


def test_generated_python_is_ruff_formatted(
    document: dict[str, Any],
    options: PythonClientOptions,
    tmp_path: Path,
) -> None:
    deployed = deepcopy(document)
    deployed["x-rpckit-binary-streams"] = [
        {
            "name": "voice",
            "url": "wss://media",
            "direction": "server-to-client",
            "frameType": "binary",
        }
    ]

    _assert_ruff_clean(deployed, options, tmp_path)


def _methods_only() -> rpc.RpcChannel:
    channel = rpc.RpcChannel("demo")

    @channel.method
    async def echo(params: _Params) -> _Result: ...

    return channel


def _events_only() -> rpc.RpcChannel:
    channel = rpc.RpcChannel("demo")

    @channel.event
    async def ticks() -> AsyncIterator[_Tick]:
        yield _Tick(n=1)

    return channel


def _methods_and_events() -> rpc.RpcChannel:
    channel = rpc.RpcChannel("demo", raises=(_MissingError,))

    @channel.method
    async def echo(params: _Params) -> _Result: ...

    @channel.event
    async def ticks() -> AsyncIterator[_Tick]:
        yield _Tick(n=1)

    return channel


def _all_stream_directions() -> rpc.RpcChannel:
    channel = rpc.RpcChannel("media")

    @channel.method
    async def echo(params: _Params) -> _Result: ...

    @channel.stream
    async def preview() -> AsyncIterator[bytes]:
        yield b""

    @channel.stream(input_content_type="audio/pcm")
    async def upload(session_id: str, frames: rpc.Inject[rpc.RpcBinaryInput]) -> None:
        pass

    @channel.stream(content_type="audio/opus")
    async def talk(
        session_id: str,
        frames: rpc.Inject[rpc.RpcBinaryInput],
        output: rpc.Inject[rpc.RpcBinaryOutput],
    ) -> None:
        pass

    return channel


@pytest.mark.parametrize(
    "channel",
    [_methods_only, _events_only, _methods_and_events, _all_stream_directions],
)
@pytest.mark.parametrize("transport", [None, "websocket"])
def test_generated_python_from_services_is_ruff_clean(
    channel: Callable[[], rpc.RpcChannel],
    transport: str | None,
    tmp_path: Path,
) -> None:
    service = rpc.RpcService()
    mounted = channel()
    service.socket("/v1/gateway", channels=[mounted])
    for stream in mounted.streams:
        local = stream.name.rsplit(".", 1)[-1]
        prefix = "/v1/{session_id}" if stream.path_parameters else "/v1"
        service.stream(f"{prefix}/{local}", stream.function)
    contract = service.contract(title="Gateway", base_url="http://localhost")

    _assert_ruff_clean(
        contract.to_openrpc(),
        PythonClientOptions(package=PACKAGE, with_transport=transport),
        tmp_path,
    )


def _assert_ruff_clean(
    document: dict[str, Any],
    options: PythonClientOptions,
    tmp_path: Path,
) -> None:
    output = tmp_path / PACKAGE
    generate_python_client(document, output, options)
    (tmp_path / "pyproject.toml").write_text(
        '[tool.ruff]\nline-length = 88\n[tool.ruff.lint]\nselect = ["E", "F", "I"]\n'
        f'[tool.ruff.lint.isort]\nknown-first-party = ["{PACKAGE}"]\n',
        encoding="utf-8",
    )

    lint = subprocess.run(
        [sys.executable, "-m", "ruff", "check", str(output)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )
    formatting = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--check", str(output)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=False,
    )

    assert lint.returncode == 0, lint.stdout + lint.stderr
    assert formatting.returncode == 0, formatting.stdout + formatting.stderr
