# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from automation_client import endpoints, models, streams
from automation_client.client import AutomationClient
from automation_client.endpoints import Endpoint, ServerName
from automation_client.internal import (
    RpcClientError,
    RpcNotificationValidationError,
    RpcRemoteError,
    RpcResponseValidationError,
    RpcTransportError,
)
from automation_client.models import (
    CreateTaskParams,
    OpenTabParams,
    StartScreencastParams,
    Tab,
    Task,
    TaskList,
    TaskUpdated,
    TaskUpdatedNotification,
)
from automation_client.namespaces import Browser, Tasks
from automation_client.streams import (
    BinaryStreamConnection,
    BinaryStreamEndpoint,
    BinaryStreamName,
    BinaryStreamOpener,
    BinaryStreamOpening,
    BinaryStreamTransport,
    BinaryWebSocketStream,
    RpcStreamsUnavailableError,
)
from automation_client.transport import WebSocketTransport

__all__ = [
    "AutomationClient",
    "BinaryStreamConnection",
    "BinaryStreamEndpoint",
    "BinaryStreamName",
    "BinaryStreamOpener",
    "BinaryStreamOpening",
    "BinaryStreamTransport",
    "BinaryWebSocketStream",
    "Browser",
    "CreateTaskParams",
    "Endpoint",
    "OpenTabParams",
    "RpcClientError",
    "RpcNotificationValidationError",
    "RpcRemoteError",
    "RpcResponseValidationError",
    "RpcStreamsUnavailableError",
    "RpcTransportError",
    "ServerName",
    "StartScreencastParams",
    "Tab",
    "Task",
    "TaskList",
    "TaskUpdated",
    "TaskUpdatedNotification",
    "Tasks",
    "WebSocketTransport",
    "endpoints",
    "models",
    "streams",
]
