# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from abc import ABC, abstractmethod
from collections.abc import Iterable

from pydantic import TypeAdapter

from automation_client.internal import RpcClientMethodDispatcher, RpcClientMethodInfo
from automation_client.models import (
    ApprovalDecision,
    ApprovalRequest,
    DialogAnswer,
    DialogRequest,
)


class TasksClientMethods(ABC):
    """Requests the server sends to this client; implement and register them."""

    @abstractmethod
    async def approve(self, params: ApprovalRequest) -> ApprovalDecision:
        """Ask the operator to approve a task action."""


class BrowserDialogsClientMethods(ABC):
    """Requests the server sends to this client; implement and register them."""

    @abstractmethod
    async def confirm(self, params: DialogRequest) -> DialogAnswer:
        """Let the operator answer a confirm() dialog of a tab."""


type ClientMethodHandler = TasksClientMethods | BrowserDialogsClientMethods

CLIENT_METHODS: tuple[RpcClientMethodInfo, ...] = (
    RpcClientMethodInfo(
        method="tasks.approve",
        owner=TasksClientMethods,
        attribute="approve",
        params_adapter=TypeAdapter(ApprovalRequest),
        result_adapter=TypeAdapter(ApprovalDecision),
        server="production",
    ),
    RpcClientMethodInfo(
        method="browser.dialogs.confirm",
        owner=BrowserDialogsClientMethods,
        attribute="confirm",
        params_adapter=TypeAdapter(DialogRequest),
        result_adapter=TypeAdapter(DialogAnswer),
        server="browser",
    ),
)


def client_method_dispatcher(
    client_methods: ClientMethodHandler | Iterable[ClientMethodHandler] = (),
) -> RpcClientMethodDispatcher:
    """Answer the server's client method requests with the given handlers."""
    return RpcClientMethodDispatcher(CLIENT_METHODS, client_methods)
