# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Mapping
from typing import Self

from automation_client.endpoints import Endpoint, ServerName, resolve_endpoints
from automation_client.internal import ClientConnection, RpcClientCore, RpcTransport
from automation_client.namespaces.browser import Browser
from automation_client.namespaces.tasks import Tasks
from automation_client.transport import WebSocketTransport


class AutomationClient:
    def __init__(
        self,
        transport: RpcTransport | Mapping[str, RpcTransport],
        *,
        close_transport: bool = True,
    ) -> None:
        self._rpc = RpcClientCore(transport, close_transport=close_transport)
        self.tasks = Tasks(self._rpc)
        self.browser = Browser(self._rpc)

    @classmethod
    def from_transport(
        cls,
        transport: RpcTransport,
        *,
        close_transport: bool = True,
    ) -> Self:
        return cls(transport, close_transport=close_transport)

    @classmethod
    def from_transports(
        cls,
        *,
        production: RpcTransport,
        browser: RpcTransport,
        streaming: RpcTransport,
    ) -> Self:
        return cls(
            {
                ServerName.PRODUCTION: production,
                ServerName.BROWSER: browser,
                ServerName.STREAMING: streaming,
            }
        )

    @classmethod
    def from_transport_map(
        cls,
        transports: Mapping[ServerName, RpcTransport],
    ) -> Self:
        return cls(transports)

    @classmethod
    def connect(
        cls,
        *endpoint_overrides: Endpoint,
        request_timeout: float | None = None,
        notification_queue_size: int = 100,
    ) -> ClientConnection[Self, ServerName]:
        return ClientConnection(
            client_factory=cls.from_transport_map,
            endpoints=resolve_endpoints(endpoint_overrides),
            transport_factory=WebSocketTransport.open,
            request_timeout=request_timeout,
            notification_queue_size=notification_queue_size,
        )

    async def close(self) -> None:
        await self._rpc.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
