# Generated by rpckit from automation.openrpc.json.
# Do not edit this file manually.

import asyncio
from collections.abc import Awaitable, Callable, Iterable, Mapping
from typing import Self

from automation_client.endpoints import Endpoint, ServerName, resolve_endpoints
from automation_client.handlers import Handler, handler_dispatcher
from automation_client.internal import (
    ClientConnection,
    RpcClientCore,
    RpcClientHook,
    RpcTransport,
    RpcTransportPool,
    RpcTransportSource,
)
from automation_client.namespaces import Browser, Tasks
from automation_client.streams import (
    BinaryStreamEndpoint,
    BinaryStreamOpener,
    BinaryStreamTransport,
    BinaryWebSocketFactory,
    BinaryWebSocketStream,
)
from automation_client.transport import WebSocketFactory, WebSocketTransport


class AutomationClient:
    def __init__(
        self,
        transport: (
            RpcTransport | Mapping[ServerName, RpcTransport] | RpcTransportSource
        ),
        *,
        close_transport: bool = True,
        hooks: Iterable[RpcClientHook] = (),
        notification_queue_size: int = 100,
        stream_opener: BinaryStreamOpener | None = None,
        variables: Mapping[str, str] | None = None,
    ) -> None:
        self._rpc = RpcClientCore(
            transport,
            close_transport=close_transport,
            hooks=hooks,
            notification_queue_size=notification_queue_size,
            stream_opener=stream_opener,
            variables=variables,
        )
        self.tasks = Tasks(self._rpc)
        self.browser = Browser(self._rpc)

    @property
    def closed(self) -> asyncio.Future[BaseException | None]:
        return self._rpc.closed

    @classmethod
    def with_transports(
        cls,
        transports: RpcTransport | Mapping[ServerName, RpcTransport],
        *,
        close_transport: bool = True,
        hooks: Iterable[RpcClientHook] = (),
        notification_queue_size: int = 100,
        stream_opener: BinaryStreamOpener | None = None,
        variables: Mapping[str, str] | None = None,
    ) -> Self:
        """Build a client on transports the caller owns, for tests and adapters."""
        return cls(
            transports,
            close_transport=close_transport,
            hooks=hooks,
            notification_queue_size=notification_queue_size,
            stream_opener=stream_opener,
            variables=variables,
        )

    @classmethod
    def connect(
        cls,
        *,
        host: str | None = None,
        servers: Mapping[ServerName, str | Endpoint] | None = None,
        request_timeout: float | None = 30.0,
        notification_queue_size: int = 100,
        notification_overflow: str = "drop_oldest",
        headers: (
            Mapping[str, str] | Callable[[], Awaitable[Mapping[str, str]]] | None
        ) = None,
        socket_factory: WebSocketFactory | None = None,
        stream_socket_factory: BinaryWebSocketFactory | None = None,
        handlers: Handler | Iterable[Handler] = (),
        hooks: Iterable[RpcClientHook] = (),
        lazy: bool = False,
        reconnect: bool = False,
        reconnect_initial_delay: float = 0.25,
        reconnect_max_delay: float = 5.0,
    ) -> ClientConnection[Self, ServerName]:
        """Connect to servers and register handlers for their requests."""

        variables: dict[str, str | None] = {
            "host": host,
        }
        dispatcher = handler_dispatcher(handlers)

        async def resolve_headers() -> Mapping[str, str] | None:
            return await headers() if callable(headers) else headers

        async def open_transport(
            endpoint_url: str,
            *,
            subprotocols: tuple[str, ...],
            request_timeout: float | None,
            notification_queue_size: int,
            notification_overflow: str,
        ) -> RpcTransport:
            return await WebSocketTransport.open(
                endpoint_url,
                subprotocols=subprotocols,
                request_timeout=request_timeout,
                notification_queue_size=notification_queue_size,
                notification_overflow=notification_overflow,
                headers=await resolve_headers(),
                socket_factory=socket_factory,
                request_handler=dispatcher,
            )

        async def open_stream(endpoint: BinaryStreamEndpoint) -> BinaryStreamTransport:
            return await BinaryWebSocketStream.open(
                endpoint,
                headers=await resolve_headers(),
                socket_factory=stream_socket_factory,
            )

        pool = RpcTransportPool(
            endpoints=resolve_endpoints(variables, servers),
            transport_factory=open_transport,
            request_timeout=request_timeout,
            notification_queue_size=notification_queue_size,
            notification_overflow=notification_overflow,
            reconnect=reconnect,
            reconnect_initial_delay=reconnect_initial_delay,
            reconnect_max_delay=reconnect_max_delay,
        )
        return ClientConnection(
            client_factory=lambda transports: cls(
                transports,
                hooks=hooks,
                notification_queue_size=notification_queue_size,
                stream_opener=open_stream,
                variables={
                    name: value
                    for name, value in variables.items()
                    if value is not None
                },
            ),
            pool=pool,
            eager=not lazy,
        )

    async def close(self) -> None:
        await self._rpc.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
