# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Awaitable, Callable, Mapping
from typing import Protocol, Self

from pyrpckit.client import RpcClientCore, RpcTransport

from automation_client.endpoints import Endpoint, ServerName, resolve_endpoints
from automation_client.namespaces.browser import Browser
from automation_client.namespaces.tasks import Tasks
from automation_client.transport import WebSocketTransport


class _Closable(Protocol):
    async def close(self) -> None: ...


class _ConnectionContext[ClientT: _Closable]:
    def __init__(
        self,
        open_client: Callable[[], Awaitable[ClientT]],
    ) -> None:
        self._open_client = open_client
        self._client: ClientT | None = None

    async def __aenter__(self) -> ClientT:
        self._client = await self._open_client()
        return self._client

    async def __aexit__(self, *args: object) -> None:
        if self._client is not None:
            await self._client.close()


class AutomationClient:
    def __init__(
        self,
        transport: RpcTransport | Mapping[str, RpcTransport],
        *,
        close_transport: bool = True,
    ) -> None:
        self._rpc = RpcClientCore(transport, close_transport=close_transport)
        self.tasks = Tasks(self._rpc)
        self.browser = Browser(self._rpc)

    @classmethod
    def from_transport(
        cls,
        transport: RpcTransport,
        *,
        close_transport: bool = True,
    ) -> Self:
        return cls(transport, close_transport=close_transport)

    @classmethod
    def from_transports(
        cls,
        *,
        production: RpcTransport,
        browser: RpcTransport,
        streaming: RpcTransport,
    ) -> Self:
        return cls(
            {
                ServerName.PRODUCTION: production,
                ServerName.BROWSER: browser,
                ServerName.STREAMING: streaming,
            }
        )

    @classmethod
    def from_transport_map(
        cls,
        transports: Mapping[ServerName, RpcTransport],
    ) -> Self:
        return cls(transports)

    @classmethod
    def connect(
        cls,
        *endpoint_overrides: Endpoint,
        request_timeout: float | None = None,
        notification_queue_size: int = 100,
    ) -> _ConnectionContext[Self]:
        return _ConnectionContext(
            lambda: cls.open(
                *endpoint_overrides,
                request_timeout=request_timeout,
                notification_queue_size=notification_queue_size,
            )
        )

    @classmethod
    async def open(
        cls,
        *endpoint_overrides: Endpoint,
        request_timeout: float | None = None,
        notification_queue_size: int = 100,
    ) -> Self:
        transports: dict[ServerName, RpcTransport] = {}
        try:
            for endpoint in resolve_endpoints(endpoint_overrides):
                transports[endpoint.server] = await WebSocketTransport.open(
                    endpoint.url,
                    subprotocols=endpoint.subprotocols,
                    request_timeout=request_timeout,
                    notification_queue_size=notification_queue_size,
                )
        except BaseException:
            for transport in transports.values():
                await transport.close()
            raise
        return cls.from_transport_map(transports)

    async def close(self) -> None:
        await self._rpc.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
