# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Iterable
from dataclasses import dataclass
from enum import StrEnum

from pyrpckit.client import RpcServerInfo, RpcServerVariable, RpcTransportDescriptor


class ServerName(StrEnum):
    PRODUCTION = "production"
    BROWSER = "browser"
    STREAMING = "streaming"


@dataclass(frozen=True, slots=True)
class Endpoint:
    server: ServerName
    url: str
    subprotocols: tuple[str, ...] = ()


_SERVERS = {
    ServerName.PRODUCTION: RpcServerInfo(
        name="production",
        url="wss://{host}/automation/rpc",
        variables={
            "host": RpcServerVariable(
                default="api.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
        ),
    ),
    ServerName.BROWSER: RpcServerInfo(
        name="browser",
        url="wss://{host}/browser/rpc",
        variables={
            "host": RpcServerVariable(
                default="browser.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
        ),
    ),
    ServerName.STREAMING: RpcServerInfo(
        name="streaming",
        url="wss://{host}/browser/stream",
        variables={
            "host": RpcServerVariable(
                default="stream.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
            subprotocols=("pyrpckit.jsonrpc",),
        ),
    ),
}


def production(
    *,
    host: str = "api.example.com",
) -> Endpoint:
    return Endpoint(
        server=ServerName.PRODUCTION,
        url=_SERVERS[ServerName.PRODUCTION].resolve(
            {
                "host": host,
            }
        ),
        subprotocols=(),
    )


def browser(
    *,
    host: str = "browser.example.com",
) -> Endpoint:
    return Endpoint(
        server=ServerName.BROWSER,
        url=_SERVERS[ServerName.BROWSER].resolve(
            {
                "host": host,
            }
        ),
        subprotocols=(),
    )


def streaming(
    *,
    host: str = "stream.example.com",
) -> Endpoint:
    return Endpoint(
        server=ServerName.STREAMING,
        url=_SERVERS[ServerName.STREAMING].resolve(
            {
                "host": host,
            }
        ),
        subprotocols=("pyrpckit.jsonrpc",),
    )


def resolve_endpoints(overrides: Iterable[Endpoint]) -> tuple[Endpoint, ...]:
    resolved = {
        ServerName.PRODUCTION: production(),
        ServerName.BROWSER: browser(),
        ServerName.STREAMING: streaming(),
    }
    supplied: set[ServerName] = set()
    for endpoint in overrides:
        if endpoint.server in supplied:
            raise ValueError(f"Duplicate endpoint for {endpoint.server!r}")
        supplied.add(endpoint.server)
        resolved[endpoint.server] = endpoint
    return tuple(resolved.values())
