# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Mapping
from dataclasses import dataclass, replace
from enum import StrEnum

from automation_client.internal import (
    RpcServerInfo,
    RpcServerVariable,
    RpcTransportDescriptor,
)


class ServerName(StrEnum):
    PRODUCTION = "production"
    BROWSER = "browser"
    STREAMING = "streaming"


@dataclass(frozen=True, slots=True)
class Endpoint:
    server: ServerName
    url: str
    subprotocols: tuple[str, ...] = ()


_SERVERS = {
    ServerName.PRODUCTION: RpcServerInfo(
        name="production",
        url="wss://{host}/automation/rpc",
        variables={
            "host": RpcServerVariable(
                default="api.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
        ),
    ),
    ServerName.BROWSER: RpcServerInfo(
        name="browser",
        url="wss://{host}/browser/rpc",
        variables={
            "host": RpcServerVariable(
                default="browser.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
        ),
    ),
    ServerName.STREAMING: RpcServerInfo(
        name="streaming",
        url="wss://{host}/browser/stream",
        variables={
            "host": RpcServerVariable(
                default="stream.example.com",
            ),
        },
        transport=RpcTransportDescriptor(
            type="websocket",
            message_encoding="json",
            subprotocols=("pyrpckit.jsonrpc",),
        ),
    ),
}


def endpoint(
    server: ServerName, values: Mapping[str, str | None] | None = None
) -> Endpoint:
    """Resolve one declared server, ignoring variables it does not declare."""
    info = _SERVERS[server]
    supplied = {
        name: value
        for name, value in (values or {}).items()
        if name in info.variables and value is not None
    }
    return Endpoint(
        server=server,
        url=info.resolve(supplied),
        subprotocols=info.transport.subprotocols if info.transport else (),
    )


def production(
    *,
    host: str = "api.example.com",
) -> Endpoint:
    return endpoint(
        ServerName.PRODUCTION,
        {
            "host": host,
        },
    )


def browser(
    *,
    host: str = "browser.example.com",
) -> Endpoint:
    return endpoint(
        ServerName.BROWSER,
        {
            "host": host,
        },
    )


def streaming(
    *,
    host: str = "stream.example.com",
) -> Endpoint:
    return endpoint(
        ServerName.STREAMING,
        {
            "host": host,
        },
    )


def resolve_endpoints(
    variables: Mapping[str, str | None] | None = None,
    overrides: Mapping[ServerName, str | Endpoint] | None = None,
) -> tuple[Endpoint, ...]:
    """Resolve every declared server, then apply the caller's overrides."""
    resolved = {server: endpoint(server, variables) for server in _SERVERS}
    for server, override in (overrides or {}).items():
        if server not in resolved:
            raise ValueError(f"Unknown server {server!r}")
        resolved[server] = (
            override
            if isinstance(override, Endpoint)
            else replace(resolved[server], url=override)
        )
    return tuple(resolved.values())
