# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from typing import Any

from pydantic import ValidationError

from automation_client.internal import RpcRemoteError

ERROR_TYPES: dict[str, type[RpcRemoteError]] = {}


def error_from_response(
    rpc_code: int,
    code: str,
    message: str,
    details: Any,
) -> RpcRemoteError:
    error_type = ERROR_TYPES.get(code)
    if error_type is None:
        return RpcRemoteError(rpc_code, code, message, details)
    adapter = getattr(error_type, "details_adapter", None)
    if adapter is not None:
        try:
            details = adapter.validate_python(details)
        except ValidationError:
            return RpcRemoteError(rpc_code, code, message, details)
    return error_type(rpc_code, code, message, details)
