# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from abc import ABC, abstractmethod
from collections.abc import Iterable

from pydantic import TypeAdapter

from automation_client.internal import RpcClientMethodDispatcher, RpcClientMethodInfo
from automation_client.models import (
    ApprovalDecision,
    ApprovalRequest,
    DialogAnswer,
    DialogRequest,
)


class TasksHandler(ABC):
    """Requests this client handles for the server; implement and register them."""

    @abstractmethod
    async def approve(self, params: ApprovalRequest) -> ApprovalDecision:
        """Ask the operator to approve a task action."""


class BrowserDialogsHandler(ABC):
    """Requests this client handles for the server; implement and register them."""

    @abstractmethod
    async def confirm(self, params: DialogRequest) -> DialogAnswer:
        """Let the operator answer a confirm() dialog of a tab."""


type Handler = TasksHandler | BrowserDialogsHandler

_HANDLER_METHODS: tuple[RpcClientMethodInfo, ...] = (
    RpcClientMethodInfo(
        method="tasks.approve",
        owner=TasksHandler,
        attribute="approve",
        params_adapter=TypeAdapter(ApprovalRequest),
        result_adapter=TypeAdapter(ApprovalDecision),
        server="production",
    ),
    RpcClientMethodInfo(
        method="browser.dialogs.confirm",
        owner=BrowserDialogsHandler,
        attribute="confirm",
        params_adapter=TypeAdapter(DialogRequest),
        result_adapter=TypeAdapter(DialogAnswer),
        server="browser",
    ),
)


def handler_dispatcher(
    handlers: Handler | Iterable[Handler] = (),
) -> RpcClientMethodDispatcher:
    """Answer the server's requests with the given handlers."""
    return RpcClientMethodDispatcher(_HANDLER_METHODS, handlers)
