# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Awaitable, Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Literal, Protocol, Self

from automation_client.internal import RpcTransportError

BinaryStreamDirection = Literal["client-to-server", "server-to-client", "bidirectional"]


class BinaryStreamName(StrEnum):
    SCREENCAST = "screencast"


@dataclass(frozen=True, slots=True)
class BinaryStreamEndpoint:
    name: BinaryStreamName
    url: str
    direction: BinaryStreamDirection
    content_type: str
    subprotocols: tuple[str, ...] = ()


class BinaryStreamTransport(Protocol):
    async def send(self, frame: bytes) -> None: ...

    async def receive(self) -> bytes: ...

    async def close(self) -> None: ...


class BinaryWebSocket(Protocol):
    async def send(self, message: bytes) -> None: ...

    async def recv(self) -> str | bytes: ...

    async def close(self) -> None: ...


class BinaryWebSocketFactory(Protocol):
    def __call__(
        self,
        url: str,
        *,
        subprotocols: list[str] | None,
    ) -> Awaitable[BinaryWebSocket]: ...


class BinaryWebSocketStream:
    def __init__(
        self,
        socket: BinaryWebSocket,
        endpoint: BinaryStreamEndpoint,
    ) -> None:
        self._socket = socket
        self.endpoint = endpoint
        self._closed = False

    @classmethod
    async def open(
        cls,
        endpoint: BinaryStreamEndpoint,
        *,
        socket_factory: BinaryWebSocketFactory | None = None,
    ) -> Self:
        if socket_factory is None:
            try:
                from websockets.asyncio.client import connect
            except ImportError as error:
                raise RuntimeError(
                    "Generated WebSocket clients require the 'websockets' package"
                ) from error
            socket_factory = connect
        socket = await socket_factory(
            endpoint.url,
            subprotocols=list(endpoint.subprotocols) or None,
        )
        return cls(socket, endpoint)

    async def send(self, frame: bytes) -> None:
        if self._closed:
            raise RpcTransportError("The binary WebSocket stream is closed")
        if self.endpoint.direction == "server-to-client":
            raise RpcTransportError("This binary stream is receive-only")
        await self._socket.send(frame)

    async def receive(self) -> bytes:
        if self._closed:
            raise RpcTransportError("The binary WebSocket stream is closed")
        if self.endpoint.direction == "client-to-server":
            raise RpcTransportError("This binary stream is send-only")
        frame = await self._socket.recv()
        if not isinstance(frame, bytes):
            raise RpcTransportError("The binary WebSocket returned a text frame")
        return frame

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._socket.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()


def screencast(
    *,
    host: str = "stream.example.com",
) -> BinaryStreamEndpoint:
    url = "wss://{host}/browser/screencast"
    url = url.replace("{host}", host)
    return BinaryStreamEndpoint(
        name=BinaryStreamName.SCREENCAST,
        url=url,
        direction="server-to-client",
        content_type="image/jpeg",
        subprotocols=("pyrpckit.binary",),
    )


binary_streams: Mapping[BinaryStreamName, BinaryStreamEndpoint] = {
    BinaryStreamName.SCREENCAST: screencast(),
}
