# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class RpcModel(BaseModel):
    model_config = ConfigDict(validate_by_name=True)


class Task(RpcModel):
    model_config = ConfigDict(extra="forbid")
    id: str
    title: str
    status: Literal["open"] | Literal["done"]


class CreateTaskParams(RpcModel):
    model_config = ConfigDict(extra="forbid")
    title: str


class Tab(RpcModel):
    model_config = ConfigDict(extra="forbid")
    id: str
    url: str


class OpenTabParams(RpcModel):
    model_config = ConfigDict(extra="forbid")
    url: str


class StartScreencastParams(RpcModel):
    model_config = ConfigDict(extra="forbid")
    quality: int = 80


class TaskUpdated(RpcModel):
    model_config = ConfigDict(extra="forbid")
    task: Task


class TaskUpdatedNotification(RpcModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal["2.0"]
    method: Literal["tasks.updated"]
    params: TaskUpdated


class Frame(RpcModel):
    model_config = ConfigDict(extra="forbid")
    sequence: int
    data: str


class FrameNotification(RpcModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal["2.0"]
    method: Literal["browser.screencast.frames"]
    params: Frame


type TaskList = list[Task]


Task.model_rebuild()
CreateTaskParams.model_rebuild()
Tab.model_rebuild()
OpenTabParams.model_rebuild()
StartScreencastParams.model_rebuild()
TaskUpdated.model_rebuild()
TaskUpdatedNotification.model_rebuild()
Frame.model_rebuild()
FrameNotification.model_rebuild()
