# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from pydantic import TypeAdapter

from automation_client.internal import RpcNotificationInfo, RpcRouteInfo
from automation_client.models import (
    Frame,
    FrameNotification,
    Tab,
    Task,
    TaskList,
    TaskUpdated,
    TaskUpdatedNotification,
)

TASKS_LIST = RpcRouteInfo(
    method="tasks.list",
    result_adapter=TypeAdapter(TaskList),
    server="production",
)

TASKS_CREATE = RpcRouteInfo(
    method="tasks.create",
    result_adapter=TypeAdapter(Task),
    server="production",
)

BROWSER_TABS_OPEN = RpcRouteInfo(
    method="browser.tabs.open",
    result_adapter=TypeAdapter(Tab),
    server="browser",
)

BROWSER_SCREENCAST_START = RpcRouteInfo(
    method="browser.screencast.start",
    result_adapter=TypeAdapter(None),
    server="streaming",
)

TASKS_UPDATED: RpcNotificationInfo[TaskUpdated] = RpcNotificationInfo(
    method="tasks.updated",
    message_adapter=TypeAdapter(TaskUpdatedNotification),
    server="production",
)

BROWSER_SCREENCAST_FRAMES: RpcNotificationInfo[Frame] = RpcNotificationInfo(
    method="browser.screencast.frames",
    message_adapter=TypeAdapter(FrameNotification),
    server="streaming",
)
