# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from pydantic import TypeAdapter

from automation_client.internal import RpcNotificationInfo, RpcRouteInfo
from automation_client.models import (
    CreateTaskParams,
    DeleteTaskParams,
    OpenTabParams,
    StartScreencastParams,
    Tab,
    Task,
    TaskList,
    TasksUpdatedNotification,
    TaskUpdated,
)

TASKS_LIST: RpcRouteInfo[None, TaskList] = RpcRouteInfo(
    method="tasks.list",
    result_adapter=TypeAdapter(TaskList),
    server="production",
)

TASKS_CREATE: RpcRouteInfo[CreateTaskParams, Task] = RpcRouteInfo(
    method="tasks.create",
    result_adapter=TypeAdapter(Task),
    server="production",
)

TASKS_DELETE: RpcRouteInfo[DeleteTaskParams, bool] = RpcRouteInfo(
    method="tasks.delete",
    result_adapter=TypeAdapter(bool),
    server="production",
)

BROWSER_TABS_OPEN: RpcRouteInfo[OpenTabParams, Tab] = RpcRouteInfo(
    method="browser.tabs.open",
    result_adapter=TypeAdapter(Tab),
    server="browser",
)

BROWSER_SCREENCAST_START: RpcRouteInfo[StartScreencastParams, None] = RpcRouteInfo(
    method="browser.screencast.start",
    result_adapter=TypeAdapter(None),
    server="streaming",
)

TASKS_UPDATED: RpcNotificationInfo[TaskUpdated] = RpcNotificationInfo(
    method="tasks.updated",
    message_adapter=TypeAdapter(TasksUpdatedNotification),
    payload_adapter=TypeAdapter(TaskUpdated),
    server="production",
)
