# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, Self

from automation_client.internal import RpcTransportError


class BinaryStreamName(StrEnum):
    SCREENCAST = "screencast"


@dataclass(frozen=True, slots=True)
class BinaryStreamEndpoint:
    name: BinaryStreamName
    url: str
    content_type: str
    subprotocols: tuple[str, ...] = ()


class BinaryStreamTransport(Protocol):
    async def receive(self) -> bytes: ...

    async def close(self) -> None: ...


type BinaryStreamOpener = Callable[
    [BinaryStreamEndpoint], Awaitable[BinaryStreamTransport]
]


class RpcStreamsUnavailableError(Exception):
    """No binary stream opener was configured for this client."""


class BinaryStreamConnection:
    def __init__(self, transport: BinaryStreamTransport) -> None:
        self._transport = transport

    async def receive(self) -> bytes:
        return await self._transport.receive()

    def __aiter__(self) -> Self:
        return self

    async def __anext__(self) -> bytes:
        try:
            return await self.receive()
        except StopAsyncIteration:
            raise

    async def close(self) -> None:
        await self._transport.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()


class BinaryStreamOpening:
    def __init__(
        self,
        endpoint: BinaryStreamEndpoint,
        opener: BinaryStreamOpener | None,
    ) -> None:
        self.endpoint = endpoint
        self._opener = opener
        self._connection: BinaryStreamConnection | None = None

    async def _open(self) -> BinaryStreamConnection:
        if self._opener is None:
            raise RpcStreamsUnavailableError(
                "No binary stream opener configured; pass stream_opener=..."
            )
        return BinaryStreamConnection(await self._opener(self.endpoint))

    def __await__(self):
        return self._open().__await__()

    async def __aenter__(self) -> BinaryStreamConnection:
        self._connection = await self._open()
        return self._connection

    async def __aexit__(self, *args: object) -> None:
        if self._connection is not None:
            await self._connection.close()


class BinaryWebSocket(Protocol):
    async def recv(self) -> str | bytes: ...

    async def close(self) -> None: ...


class BinaryWebSocketFactory(Protocol):
    def __call__(
        self,
        url: str,
        *,
        subprotocols: list[str] | None,
    ) -> Awaitable[BinaryWebSocket]: ...


class BinaryWebSocketStream:
    def __init__(self, socket: BinaryWebSocket) -> None:
        self._socket = socket

    @classmethod
    async def open(
        cls,
        endpoint: BinaryStreamEndpoint,
        *,
        socket_factory: BinaryWebSocketFactory | None = None,
    ) -> Self:
        if socket_factory is None:
            try:
                from websockets.asyncio.client import connect
            except ImportError as error:
                raise RuntimeError(
                    "Generated WebSocket clients require the 'websockets' package"
                ) from error
            socket_factory = connect
        socket = await socket_factory(
            endpoint.url,
            subprotocols=list(endpoint.subprotocols) or None,
        )
        return cls(socket)

    async def receive(self) -> bytes:
        frame = await self._socket.recv()
        if not isinstance(frame, bytes):
            raise RpcTransportError("The binary WebSocket returned a text frame")
        return frame

    async def close(self) -> None:
        await self._socket.close()


BINARY_STREAMS: Mapping[BinaryStreamName, BinaryStreamEndpoint] = {
    BinaryStreamName.SCREENCAST: BinaryStreamEndpoint(
        name=BinaryStreamName.SCREENCAST,
        url="wss://{host}/browser/screencast",
        content_type="image/jpeg",
        subprotocols=("pyrpckit.binary",),
    ),
}
