# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.

import asyncio
from collections.abc import AsyncIterator, Awaitable, Callable, Mapping
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from enum import StrEnum
from types import MappingProxyType
from typing import Any, Literal, Protocol, Self

from pydantic import BaseModel, ConfigDict

from automation_client.internal import (
    RpcServerVariable,
    RpcStreamClosed,
    RpcStreamFailed,
    RpcStreamRefused,
    RpcStreamsUnavailableError,
    RpcTransportError,
    resolve_url_template,
)


class BinaryStreamName(StrEnum):
    BROWSER_SCREENCAST_FRAMES = "browser.screencast.frames"
    BROWSER_SCREENCAST_UPLOAD = "browser.screencast.upload"
    BROWSER_SCREENCAST_CONTROL = "browser.screencast.control"


type BinaryStreamDirection = Literal[
    "server-to-client", "client-to-server", "bidirectional"
]


@dataclass(frozen=True, slots=True)
class BinaryStreamEndpoint:
    name: BinaryStreamName
    url: str
    content_type: str | None = None
    subprotocols: tuple[str, ...] = ()
    direction: BinaryStreamDirection = "server-to-client"
    input_content_type: str | None = None


@dataclass(frozen=True, slots=True)
class BinaryStreamInfo:
    """One declared binary stream, before its variables are filled in."""

    name: BinaryStreamName
    url: str
    content_type: str | None = None
    direction: BinaryStreamDirection = "server-to-client"
    subprotocols: tuple[str, ...] = ()
    variables: Mapping[str, RpcServerVariable] = field(default_factory=dict)
    input_content_type: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "variables", MappingProxyType(dict(self.variables)))


def resolve_stream_endpoint(
    stream: BinaryStreamInfo,
    connected: Mapping[str, str] | None = None,
    values: Mapping[str, str | None] | None = None,
) -> BinaryStreamEndpoint:
    """Fill a stream URL from the call's values, then the client's connect values."""
    supplied = {
        **{
            name: value
            for name, value in (connected or {}).items()
            if name in stream.variables
        },
        **{name: value for name, value in (values or {}).items() if value is not None},
    }
    return BinaryStreamEndpoint(
        name=stream.name,
        url=resolve_url_template(
            f"binary stream {stream.name.value!r}",
            stream.url,
            stream.variables,
            supplied,
        ),
        content_type=stream.content_type,
        subprotocols=stream.subprotocols,
        direction=stream.direction,
        input_content_type=stream.input_content_type,
    )


class BinaryInputEnd(BaseModel):
    """The text message that ends a stream's input; output keeps flowing."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    type: Literal["end"]


class BinaryStreamTransport(Protocol):
    async def receive(self) -> bytes: ...

    async def close(self) -> None: ...


class BinaryInputTransport(BinaryStreamTransport, Protocol):
    """A stream transport that can also send frames to the server."""

    async def send(self, frame: bytes) -> None: ...

    async def end_input(self) -> None: ...


type BinaryStreamOpener = Callable[
    [BinaryStreamEndpoint], Awaitable[BinaryStreamTransport]
]


class _ManagedBinaryStream(Protocol):
    async def __aenter__(self) -> Self: ...

    async def __aexit__(self, error_type: object, *args: object) -> None: ...


class BinaryReceiver:
    """Receives the frames of a server-to-client stream."""

    def __init__(self, transport: BinaryStreamTransport) -> None:
        self._transport = transport

    async def receive(self) -> bytes:
        return await self._transport.receive()

    def __aiter__(self) -> Self:
        return self

    async def __anext__(self) -> bytes:
        try:
            return await self.receive()
        except RpcStreamClosed:
            raise StopAsyncIteration from None

    async def close(self) -> None:
        await self._transport.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, error_type: object, *args: object) -> None:
        await self.close()


class BinaryChannel(BinaryReceiver):
    """Sends and receives frames concurrently on a bidirectional stream."""

    def __init__(self, transport: BinaryInputTransport) -> None:
        super().__init__(transport)
        self._input = transport
        self._input_ended = False

    async def send(self, frame: bytes | bytearray | memoryview) -> None:
        """Send one frame; waits while the transport applies backpressure."""
        if self._input_ended:
            raise RpcStreamClosed("The binary input already ended")
        await self._input.send(bytes(frame))

    async def end_input(self) -> None:
        """Tell the server that no more frames follow; output keeps flowing."""
        if self._input_ended:
            raise RpcStreamClosed("The binary input already ended")
        self._input_ended = True
        await self._input.end_input()


class BinarySender:
    """Sends the frames of a client-to-server stream.

    Leaving ``async with`` normally ends the input and waits for the server's
    close; leaving it with an exception aborts the stream instead.
    """

    def __init__(self, transport: BinaryInputTransport) -> None:
        self._transport = transport
        self._input_ended = False

    async def send(self, frame: bytes | bytearray | memoryview) -> None:
        """Send one frame; waits while the transport applies backpressure."""
        if self._input_ended:
            raise RpcStreamClosed("The binary input already ended")
        await self._transport.send(bytes(frame))

    async def end(self, *, timeout: float | None = 30.0) -> None:
        """End the input and wait until the server accepted it by closing.

        Raises ``TimeoutError`` when the server has not closed the stream after
        ``timeout`` seconds; ``None`` waits without a limit.
        """
        async with asyncio.timeout(timeout):
            if not self._input_ended:
                self._input_ended = True
                await self._transport.end_input()
            try:
                await self._transport.receive()
            except RpcStreamClosed:
                return
        raise RpcTransportError("The server sent a frame on a client-to-server stream")

    async def close(self) -> None:
        await self._transport.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, error_type: object, *args: object) -> None:
        try:
            if error_type is None:
                await self.end()
        finally:
            await self.close()


@asynccontextmanager
async def open_binary_stream[StreamT: _ManagedBinaryStream](
    endpoint: BinaryStreamEndpoint,
    opener: BinaryStreamOpener | None,
    stream_type: Callable[[Any], StreamT],
) -> AsyncIterator[StreamT]:
    """Open a stream for one ``async with`` block and close it when it ends."""
    if opener is None:
        raise RpcStreamsUnavailableError(
            "No binary stream opener configured; pass stream_opener=..."
        )
    transport = await opener(endpoint)
    if endpoint.direction != "server-to-client" and not (
        hasattr(transport, "send") and hasattr(transport, "end_input")
    ):
        await transport.close()
        raise RpcStreamsUnavailableError(
            f"The binary stream {endpoint.name.value!r} sends frames, "
            "but the stream opener returned a transport without send() "
            "and end_input()"
        )
    async with stream_type(transport) as stream:
        yield stream


class BinaryWebSocket(Protocol):
    async def recv(self) -> str | bytes: ...

    async def send(self, message: str | bytes) -> None: ...

    async def close(self) -> None: ...


class BinaryWebSocketFactory(Protocol):
    def __call__(
        self,
        url: str,
        *,
        subprotocols: list[str] | None,
        additional_headers: Mapping[str, str] | None,
    ) -> Awaitable[BinaryWebSocket]: ...


class BinaryWebSocketStream:
    def __init__(self, socket: BinaryWebSocket) -> None:
        self._socket = socket
        self._closed = False

    @classmethod
    async def open(
        cls,
        endpoint: BinaryStreamEndpoint,
        *,
        headers: Mapping[str, str] | None = None,
        socket_factory: BinaryWebSocketFactory | None = None,
    ) -> Self:
        if socket_factory is None:
            try:
                from websockets.asyncio.client import connect
            except ImportError as error:
                raise RuntimeError(
                    "Generated WebSocket clients require the 'websockets' package"
                ) from error
            socket_factory = connect
        socket = await socket_factory(
            endpoint.url,
            subprotocols=list(endpoint.subprotocols) or None,
            additional_headers=headers,
        )
        return cls(socket)

    async def receive(self) -> bytes:
        if self._closed:
            raise RpcStreamClosed("The binary stream is closed")
        try:
            frame = await self._socket.recv()
        except Exception as error:
            self._raise_closed(error)
            raise
        if not isinstance(frame, bytes):
            raise RpcTransportError("The binary WebSocket returned a text frame")
        return frame

    async def send(self, frame: bytes) -> None:
        if self._closed:
            raise RpcStreamClosed("The binary stream is closed")
        try:
            await self._socket.send(frame)
        except Exception as error:
            self._raise_closed(error)
            raise

    async def end_input(self) -> None:
        if self._closed:
            raise RpcStreamClosed("The binary stream is closed")
        try:
            await self._socket.send(BinaryInputEnd(type="end").model_dump_json())
        except Exception as error:
            self._raise_closed(error)
            raise

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._socket.close()

    def _raise_closed(self, error: Exception) -> None:
        try:
            from websockets.exceptions import ConnectionClosed, ConnectionClosedOK
        except ImportError:
            return
        if not isinstance(error, ConnectionClosed):
            return
        self._closed = True
        if isinstance(error, ConnectionClosedOK):
            raise RpcStreamClosed("The server closed the binary stream") from None
        close = error.rcvd
        code = 1006 if close is None else close.code
        reason = "" if close is None else close.reason
        failure = RpcStreamRefused if code == 1008 else RpcStreamFailed
        raise failure(code, reason) from error


BINARY_STREAMS: Mapping[BinaryStreamName, BinaryStreamInfo] = {
    BinaryStreamName.BROWSER_SCREENCAST_FRAMES: BinaryStreamInfo(
        name=BinaryStreamName.BROWSER_SCREENCAST_FRAMES,
        url="wss://{host}/browser/screencast",
        content_type="image/jpeg",
        variables={
            "host": RpcServerVariable(
                default="api.example.com",
            ),
        },
    ),
    BinaryStreamName.BROWSER_SCREENCAST_UPLOAD: BinaryStreamInfo(
        name=BinaryStreamName.BROWSER_SCREENCAST_UPLOAD,
        url="wss://{host}/browser/screencast/upload",
        direction="client-to-server",
        input_content_type="video/webm",
        variables={
            "host": RpcServerVariable(
                default="api.example.com",
            ),
        },
    ),
    BinaryStreamName.BROWSER_SCREENCAST_CONTROL: BinaryStreamInfo(
        name=BinaryStreamName.BROWSER_SCREENCAST_CONTROL,
        url="wss://{host}/browser/screencast/control",
        content_type="image/jpeg",
        direction="bidirectional",
        input_content_type="application/x-input-event",
        variables={
            "host": RpcServerVariable(
                default="api.example.com",
            ),
        },
    ),
}
