# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, Self

from automation_client.internal import (
    RpcStreamClosed,
    RpcStreamsUnavailableError,
    RpcTransportError,
)


class BinaryStreamName(StrEnum):
    BROWSER_SCREENCAST_FRAMES = "browser.screencast.frames"


@dataclass(frozen=True, slots=True)
class BinaryStreamEndpoint:
    name: BinaryStreamName
    url: str
    content_type: str
    subprotocols: tuple[str, ...] = ()


class BinaryStreamTransport(Protocol):
    async def receive(self) -> bytes: ...

    async def close(self) -> None: ...


type BinaryStreamOpener = Callable[
    [BinaryStreamEndpoint], Awaitable[BinaryStreamTransport]
]


class BinaryStreamConnection:
    def __init__(self, transport: BinaryStreamTransport) -> None:
        self._transport = transport

    async def receive(self) -> bytes:
        return await self._transport.receive()

    def __aiter__(self) -> Self:
        return self

    async def __anext__(self) -> bytes:
        try:
            return await self.receive()
        except RpcStreamClosed:
            raise StopAsyncIteration from None

    async def close(self) -> None:
        await self._transport.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()


class BinaryStreamOpening:
    """A stream that is opened by ``async with`` or by ``await ....open()``.

    Both forms hand out a connection the caller has to close; only the context
    manager does it for them.
    """

    def __init__(
        self,
        endpoint: BinaryStreamEndpoint,
        opener: BinaryStreamOpener | None,
    ) -> None:
        self.endpoint = endpoint
        self._opener = opener
        self._connection: BinaryStreamConnection | None = None

    async def open(self) -> BinaryStreamConnection:
        if self._opener is None:
            raise RpcStreamsUnavailableError(
                "No binary stream opener configured; pass stream_opener=..."
            )
        return BinaryStreamConnection(await self._opener(self.endpoint))

    async def __aenter__(self) -> BinaryStreamConnection:
        self._connection = await self.open()
        return self._connection

    async def __aexit__(self, *args: object) -> None:
        connection, self._connection = self._connection, None
        if connection is not None:
            await connection.close()


class BinaryWebSocket(Protocol):
    async def recv(self) -> str | bytes: ...

    async def close(self) -> None: ...


class BinaryWebSocketFactory(Protocol):
    def __call__(
        self,
        url: str,
        *,
        subprotocols: list[str] | None,
    ) -> Awaitable[BinaryWebSocket]: ...


class BinaryWebSocketStream:
    def __init__(self, socket: BinaryWebSocket) -> None:
        self._socket = socket
        self._closed = False

    @classmethod
    async def open(
        cls,
        endpoint: BinaryStreamEndpoint,
        *,
        socket_factory: BinaryWebSocketFactory | None = None,
    ) -> Self:
        if socket_factory is None:
            try:
                from websockets.asyncio.client import connect
            except ImportError as error:
                raise RuntimeError(
                    "Generated WebSocket clients require the 'websockets' package"
                ) from error
            socket_factory = connect
        socket = await socket_factory(
            endpoint.url,
            subprotocols=list(endpoint.subprotocols) or None,
        )
        return cls(socket)

    async def receive(self) -> bytes:
        if self._closed:
            raise RpcStreamClosed("The binary stream is closed")
        try:
            frame = await self._socket.recv()
        except Exception as error:
            if _closed_normally(error):
                self._closed = True
                raise RpcStreamClosed("The server closed the binary stream") from None
            raise
        if not isinstance(frame, bytes):
            raise RpcTransportError("The binary WebSocket returned a text frame")
        return frame

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._socket.close()


def _closed_normally(error: Exception) -> bool:
    try:
        from websockets.exceptions import ConnectionClosedOK
    except ImportError:
        return False
    return isinstance(error, ConnectionClosedOK)


BINARY_STREAMS: Mapping[BinaryStreamName, BinaryStreamEndpoint] = {
    BinaryStreamName.BROWSER_SCREENCAST_FRAMES: BinaryStreamEndpoint(
        name=BinaryStreamName.BROWSER_SCREENCAST_FRAMES,
        url="wss://{host}/browser/screencast",
        content_type="image/jpeg",
        subprotocols=("pyrpckit.binary",),
    ),
}
