# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
import asyncio
import json
from collections.abc import AsyncIterator, Awaitable
from typing import Any, Protocol, Self

from automation_client.internal import RpcRemoteError, RpcTransportError

type JsonObject = dict[str, Any]
_STREAM_ENDED = object()


class WebSocket(Protocol):
    async def send(self, message: str) -> None: ...

    async def recv(self) -> str | bytes: ...

    async def close(self) -> None: ...


class WebSocketFactory(Protocol):
    def __call__(
        self,
        url: str,
        *,
        subprotocols: list[str] | None,
    ) -> Awaitable[WebSocket]: ...


class WebSocketTransport:
    def __init__(
        self,
        socket: WebSocket,
        *,
        request_timeout: float | None = None,
        notification_queue_size: int = 100,
    ) -> None:
        if notification_queue_size <= 0:
            raise ValueError("notification_queue_size must be positive")
        self._socket = socket
        self._request_timeout = request_timeout
        self._notifications: asyncio.Queue[object] = asyncio.Queue(
            notification_queue_size
        )
        self._pending: dict[int, asyncio.Future[Any]] = {}
        self._next_request_id = 1
        self._closed = False
        self._reader = asyncio.create_task(self._receive())

    @classmethod
    async def open(
        cls,
        url: str,
        *,
        subprotocols: tuple[str, ...] = (),
        request_timeout: float | None = None,
        notification_queue_size: int = 100,
        socket_factory: WebSocketFactory | None = None,
    ) -> Self:
        if socket_factory is None:
            try:
                from websockets.asyncio.client import connect
            except ImportError as error:
                raise RuntimeError(
                    "Generated WebSocket clients require the 'websockets' package"
                ) from error
            socket_factory = connect
        socket = await socket_factory(
            url,
            subprotocols=list(subprotocols) or None,
        )
        return cls(
            socket,
            request_timeout=request_timeout,
            notification_queue_size=notification_queue_size,
        )

    async def request(
        self,
        method: str,
        params: JsonObject | None = None,
    ) -> Any:
        if self._closed:
            raise RpcTransportError("The WebSocket transport is closed")
        request_id = self._next_request_id
        self._next_request_id += 1
        response = asyncio.get_running_loop().create_future()
        self._pending[request_id] = response
        message: JsonObject = {
            "jsonrpc": "2.0",
            "id": request_id,
            "method": method,
        }
        if params is not None:
            message["params"] = params
        try:
            await self._socket.send(json.dumps(message, separators=(",", ":")))
            async with asyncio.timeout(self._request_timeout):
                return await asyncio.shield(response)
        except TimeoutError as error:
            raise RpcTransportError(f"RPC request {method!r} timed out") from error
        finally:
            self._pending.pop(request_id, None)

    async def notifications(self) -> AsyncIterator[JsonObject]:
        while True:
            item = await self._notifications.get()
            if item is _STREAM_ENDED:
                return
            if isinstance(item, BaseException):
                raise RpcTransportError(
                    "The WebSocket notification stream failed"
                ) from item
            assert isinstance(item, dict)
            yield item

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._socket.close()
        self._reader.cancel()
        await asyncio.gather(self._reader, return_exceptions=True)
        self._fail_pending(RpcTransportError("The WebSocket transport was closed"))

    async def _receive(self) -> None:
        failure: BaseException | None = None
        try:
            while True:
                message = self._decode(await self._socket.recv())
                if "id" in message:
                    self._resolve_response(message)
                elif isinstance(message.get("method"), str):
                    try:
                        self._notifications.put_nowait(message)
                    except asyncio.QueueFull as error:
                        raise RpcTransportError(
                            "The WebSocket notification queue overflowed"
                        ) from error
                else:
                    raise RpcTransportError("Invalid JSON-RPC message")
        except asyncio.CancelledError:
            return
        except BaseException as error:
            failure = error
            self._closed = True
            self._fail_pending(error)
        finally:
            self._finish_notifications(failure)

    @staticmethod
    def _decode(raw: str | bytes) -> JsonObject:
        try:
            message = json.loads(raw)
        except (TypeError, UnicodeDecodeError, json.JSONDecodeError) as error:
            raise RpcTransportError("The WebSocket returned invalid JSON") from error
        if not isinstance(message, dict) or message.get("jsonrpc") != "2.0":
            raise RpcTransportError("Invalid JSON-RPC message")
        return message

    def _resolve_response(self, message: JsonObject) -> None:
        request_id = message["id"]
        if not isinstance(request_id, int) or isinstance(request_id, bool):
            raise RpcTransportError("JSON-RPC response IDs must be integers")
        response = self._pending.get(request_id)
        if response is None or response.done():
            raise RpcTransportError(f"Unknown JSON-RPC response ID: {request_id!r}")
        error = message.get("error")
        if isinstance(error, dict):
            response.set_exception(
                RpcRemoteError(
                    int(error.get("code", 0)),
                    str(error.get("message", "Remote RPC error")),
                    error.get("data"),
                )
            )
        elif "result" in message:
            response.set_result(message["result"])
        else:
            raise RpcTransportError("JSON-RPC response has no result or error")

    def _fail_pending(self, error: BaseException) -> None:
        for response in self._pending.values():
            if not response.done():
                response.set_exception(error)
        self._pending.clear()

    def _finish_notifications(self, failure: BaseException | None) -> None:
        if self._notifications.full():
            self._notifications.get_nowait()
        self._notifications.put_nowait(failure or _STREAM_ENDED)
