# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
import asyncio
from collections.abc import AsyncIterator, Iterable, Mapping
from typing import Any, Protocol, TypeVar

from pydantic import ValidationError

from .errors import (
    RpcNotificationValidationError,
    RpcResponseValidationError,
    RpcTransportError,
)
from .metadata import JsonValue, RpcNotificationInfo, RpcRouteInfo
from .transport import RpcTransport

ResultT = TypeVar("ResultT")
_STREAM_ENDED = object()


class RpcClientHook(Protocol):
    async def before_request(
        self,
        route: RpcRouteInfo[Any],
        params: JsonValue,
    ) -> None: ...

    async def after_response(
        self,
        route: RpcRouteInfo[Any],
        result: JsonValue,
    ) -> None: ...


class RpcClientCore:
    def __init__(
        self,
        transports: RpcTransport | Mapping[str, RpcTransport],
        *,
        close_transport: bool = True,
        hooks: Iterable[RpcClientHook] = (),
    ) -> None:
        self._single_transport = None if isinstance(transports, Mapping) else transports
        self._transports = dict(transports) if isinstance(transports, Mapping) else {}
        self._close_transport = close_transport
        self._hooks = tuple(hooks)
        self._closed = False
        self._streams: dict[
            int,
            list[tuple[str | None, asyncio.Queue[object]]],
        ] = {}
        self._stream_tasks: dict[int, asyncio.Task[None]] = {}

    async def request(
        self,
        route: RpcRouteInfo[ResultT],
        *,
        params: dict[str, Any] | None = None,
    ) -> ResultT:
        for hook in self._hooks:
            await hook.before_request(route, params)
        transport = self._transport_for(route.server)
        result = await transport.request(route.method, params)
        for hook in reversed(self._hooks):
            await hook.after_response(route, result)
        try:
            return route.result_adapter.validate_python(result)
        except ValidationError as error:
            raise RpcResponseValidationError(route.method, error) from error

    def notifications(
        self,
        method: str | None = None,
        *,
        server: str | None = None,
    ) -> AsyncIterator[dict[str, Any]]:
        return self._notifications(method, server)

    def subscribe[PayloadT](
        self,
        notification: RpcNotificationInfo[PayloadT],
    ) -> AsyncIterator[PayloadT]:
        return self._subscribe(notification)

    async def _subscribe[PayloadT](
        self,
        notification: RpcNotificationInfo[PayloadT],
    ) -> AsyncIterator[PayloadT]:
        async for message in self.notifications(
            notification.method,
            server=notification.server,
        ):
            try:
                envelope = notification.message_adapter.validate_python(message)
            except ValidationError as error:
                raise RpcNotificationValidationError(
                    notification.method,
                    error,
                ) from error
            yield envelope.params

    async def _notifications(
        self,
        method: str | None,
        server: str | None,
    ) -> AsyncIterator[dict[str, Any]]:
        transport = self._transport_for(server)
        key = id(transport)
        queue: asyncio.Queue[object] = asyncio.Queue()
        subscribers = self._streams.setdefault(key, [])
        subscriber = (method, queue)
        subscribers.append(subscriber)
        if key not in self._stream_tasks:
            self._stream_tasks[key] = asyncio.create_task(
                self._pump_notifications(key, transport)
            )
        try:
            while True:
                item = await queue.get()
                if item is _STREAM_ENDED:
                    return
                if isinstance(item, BaseException):
                    raise RpcTransportError("The notification stream failed") from item
                assert isinstance(item, dict)
                yield item
        finally:
            subscribers.remove(subscriber)

    async def _pump_notifications(
        self,
        key: int,
        transport: RpcTransport,
    ) -> None:
        terminal: object = _STREAM_ENDED
        try:
            async for message in transport.notifications():
                message_method = message.get("method")
                for method, queue in tuple(self._streams[key]):
                    if method is None or method == message_method:
                        queue.put_nowait(message)
        except asyncio.CancelledError:
            raise
        except BaseException as error:
            terminal = error
        finally:
            for _, queue in tuple(self._streams.get(key, ())):
                queue.put_nowait(terminal)

    async def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        tasks = tuple(self._stream_tasks.values())
        for task in tasks:
            task.cancel()
        if tasks:
            await asyncio.gather(*tasks, return_exceptions=True)
        if self._close_transport:
            transports = (
                (self._single_transport,)
                if self._single_transport is not None
                else tuple(dict.fromkeys(self._transports.values()))
            )
            await asyncio.gather(*(transport.close() for transport in transports))

    def _transport_for(self, server: str | None) -> RpcTransport:
        if self._closed:
            raise RpcTransportError("The RPC client is closed")
        if self._single_transport is not None:
            return self._single_transport
        if server is not None:
            try:
                return self._transports[server]
            except KeyError as error:
                raise RpcTransportError(
                    f"No transport is configured for server {server!r}"
                ) from error
        if len(self._transports) == 1:
            return next(iter(self._transports.values()))
        raise RpcTransportError(
            "The route has no server and cannot be dispatched across "
            "multiple transports"
        )
