# Generated by rpckit from automation.openrpc.json.
# Do not edit this file manually.
from typing import Any

from pydantic import ValidationError


class RpcClientError(Exception):
    """Base error raised by the client."""


class RpcRemoteError(RpcClientError):
    def __init__(
        self,
        rpc_code: int,
        code: str,
        message: str,
        details: Any = None,
    ) -> None:
        super().__init__(f"RPC error {code or rpc_code}: {message}")
        self.rpc_code = rpc_code
        self.code = code
        self.message = message
        self.details = details


class RpcParseError(RpcRemoteError):
    code = "parse_error"


class RpcInvalidRequestError(RpcRemoteError):
    code = "invalid_request"


class RpcMethodNotFoundError(RpcRemoteError):
    code = "method_not_found"


class RpcInvalidParamsError(RpcRemoteError):
    code = "invalid_params"


class RpcInternalError(RpcRemoteError):
    code = "internal_error"


class RpcConnectionClosed(RpcClientError):
    def __init__(self, code: int | None, reason: str) -> None:
        super().__init__(f"RPC connection closed ({code}): {reason}")
        self.code = code
        self.reason = reason


class RpcTransportError(RpcClientError):
    """Raised when the connection cannot serve a request."""


class RpcStreamsUnavailableError(RpcClientError):
    """No binary stream opener was configured for this client."""


class RpcStreamClosed(RpcClientError):
    """Raised when a binary stream ended because the server closed it."""


class RpcStreamFailed(RpcClientError):
    """Raised when the server closed a binary stream with an error code."""

    def __init__(self, code: int, reason: str = "") -> None:
        super().__init__(
            f"The binary stream closed with code {code}"
            + (f": {reason}" if reason else "")
        )
        self.code = code
        self.reason = reason


class RpcStreamRefused(RpcStreamFailed):
    """Raised when the server refused a binary stream by policy (1008)."""


class RpcResponseValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid response for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error


class RpcNotificationValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid notification for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error
