# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from typing import Any, ClassVar

from pydantic import ValidationError


class RpcClientError(Exception):
    """Base error raised by the client."""


class RpcRemoteError(RpcClientError):
    code: ClassVar[str] = ""

    def __init__(
        self,
        rpc_code: int,
        code: str,
        message: str,
        details: Any = None,
    ) -> None:
        super().__init__(f"RPC error {code or rpc_code}: {message}")
        self.rpc_code = rpc_code
        self.code = code
        self.message = message
        self.details = details


class RpcParseError(RpcRemoteError):
    code = "parse_error"


class RpcInvalidRequestError(RpcRemoteError):
    code = "invalid_request"


class RpcMethodNotFoundError(RpcRemoteError):
    code = "method_not_found"


class RpcInvalidParamsError(RpcRemoteError):
    code = "invalid_params"


class RpcInternalError(RpcRemoteError):
    code = "internal_error"


class RpcConnectionClosed(RpcClientError):
    def __init__(self, code: int | None, reason: str) -> None:
        super().__init__(f"RPC connection closed ({code}): {reason}")
        self.code = code
        self.reason = reason


class RpcTransportError(RpcClientError):
    """Raised when the connection cannot serve a request."""


class RpcResponseValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid response for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error


class RpcNotificationValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid notification for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error
