# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from typing import Any

from pydantic import ValidationError


class RpcClientError(Exception):
    """Base error raised by the client."""


class RpcRemoteError(RpcClientError):
    def __init__(self, code: int, message: str, data: Any = None) -> None:
        super().__init__(f"RPC error {code}: {message}")
        self.code = code
        self.message = message
        self.data = data


class RpcTransportError(RpcClientError):
    """Raised when the connection cannot serve a request."""


class RpcResponseValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid response for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error


class RpcNotificationValidationError(RpcClientError):
    def __init__(self, method: str, error: ValidationError) -> None:
        super().__init__(f"Invalid notification for RPC method {method!r}: {error}")
        self.method = method
        self.validation_error = error
