# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any

from pydantic import TypeAdapter


@dataclass(frozen=True, slots=True)
class RpcContractInfo:
    title: str
    version: str
    protocol_version: int | None = None


@dataclass(frozen=True, slots=True)
class RpcRouteInfo[ResultT]:
    method: str
    result_adapter: TypeAdapter[ResultT]
    server: str | None = None


@dataclass(frozen=True, slots=True)
class RpcNotificationInfo[PayloadT]:
    method: str
    message_adapter: TypeAdapter[Any]
    server: str | None = None


@dataclass(frozen=True, slots=True)
class RpcServerVariable:
    default: str
    description: str = ""
    enum: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if self.enum and self.default not in self.enum:
            raise ValueError(
                "The server variable default must be one of its enum values"
            )


@dataclass(frozen=True, slots=True)
class RpcTransportDescriptor:
    type: str
    message_encoding: str | None = None
    subprotocols: tuple[str, ...] = ()
    options: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "options", MappingProxyType(dict(self.options)))


@dataclass(frozen=True, slots=True)
class RpcServerInfo:
    name: str
    url: str
    summary: str = ""
    description: str = ""
    variables: Mapping[str, RpcServerVariable] = field(default_factory=dict)
    transport: RpcTransportDescriptor | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "variables", MappingProxyType(dict(self.variables)))

    def resolve(self, values: Mapping[str, str] | None = None, /, **kwargs: str) -> str:
        supplied = {**dict(values or {}), **kwargs}
        unknown = sorted(set(supplied) - set(self.variables))
        if unknown:
            raise ValueError(
                f"Unknown variables for server {self.name!r}: {', '.join(unknown)}"
            )
        resolved = self.url
        for name, variable in self.variables.items():
            value = supplied.get(name, variable.default)
            if variable.enum and value not in variable.enum:
                raise ValueError(
                    f"Invalid value {value!r} for server variable {name!r}; "
                    f"expected one of {variable.enum!r}"
                )
            resolved = resolved.replace(f"{{{name}}}", value)
        return resolved


type JsonValue = (
    None | bool | int | float | str | list["JsonValue"] | dict[str, "JsonValue"]
)
