# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
class UnsetType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "UNSET"


UNSET = UnsetType()
