# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from contextlib import AbstractAsyncContextManager

from automation_client.internal import UNSET, RpcClientCore, UnsetType
from automation_client.models import OpenTabParams, StartScreencastParams, Tab
from automation_client.routes import BROWSER_SCREENCAST_START, BROWSER_TABS_OPEN
from automation_client.streams import (
    BINARY_STREAMS,
    BinaryChannel,
    BinaryReceiver,
    BinarySender,
    BinaryStreamName,
    open_binary_stream,
    resolve_stream_endpoint,
)


class BrowserTabs:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def open(
        self,
        *,
        url: str,
    ) -> Tab:
        """Open a browser tab."""
        params = OpenTabParams(
            url=url,
        )
        return await self._rpc.request(
            BROWSER_TABS_OPEN,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )


class BrowserScreencast:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def start(
        self,
        *,
        quality: int | UnsetType = UNSET,
    ) -> None:
        """Start the browser screencast."""
        values: dict[str, object] = {}
        if quality is not UNSET:
            values["quality"] = quality
        params = StartScreencastParams.model_validate(values)
        await self._rpc.request(
            BROWSER_SCREENCAST_START,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )

    def frames(
        self,
        *,
        host: str | None = None,
        url: str | None = None,
    ) -> AbstractAsyncContextManager[BinaryReceiver]:
        """Raw screencast frames as binary WebSocket messages."""
        return open_binary_stream(
            resolve_stream_endpoint(
                BINARY_STREAMS[BinaryStreamName.BROWSER_SCREENCAST_FRAMES],
                {
                    "host": host,
                },
                url=url,
                defaults=self._rpc.variables,
            ),
            self._rpc.stream_opener,
            BinaryReceiver,
        )

    def upload(
        self,
        *,
        host: str | None = None,
        url: str | None = None,
    ) -> AbstractAsyncContextManager[BinarySender]:
        """Upload a recorded screencast as binary WebSocket messages."""
        return open_binary_stream(
            resolve_stream_endpoint(
                BINARY_STREAMS[BinaryStreamName.BROWSER_SCREENCAST_UPLOAD],
                {
                    "host": host,
                },
                url=url,
                defaults=self._rpc.variables,
            ),
            self._rpc.stream_opener,
            BinarySender,
        )

    def control(
        self,
        *,
        host: str | None = None,
        url: str | None = None,
    ) -> AbstractAsyncContextManager[BinaryChannel]:
        """Receive frames while sending input events back."""
        return open_binary_stream(
            resolve_stream_endpoint(
                BINARY_STREAMS[BinaryStreamName.BROWSER_SCREENCAST_CONTROL],
                {
                    "host": host,
                },
                url=url,
                defaults=self._rpc.variables,
            ),
            self._rpc.stream_opener,
            BinaryChannel,
        )


class Browser:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc
        self.tabs = BrowserTabs(rpc)
        self.screencast = BrowserScreencast(rpc)
