# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from automation_client.internal import UNSET, RpcClientCore, UnsetType
from automation_client.models import OpenTabParams, StartScreencastParams, Tab
from automation_client.routes import BROWSER_SCREENCAST_START, BROWSER_TABS_OPEN


class BrowserTabs:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def open(
        self,
        *,
        url: str,
    ) -> Tab:
        """Open a browser tab."""
        params = OpenTabParams(
            url=url,
        )
        return await self._rpc.request(
            BROWSER_TABS_OPEN,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )


class BrowserScreencast:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def start(
        self,
        *,
        quality: int | UnsetType = UNSET,
    ) -> None:
        """Start the browser screencast."""
        values: dict[str, object] = {}
        if quality is not UNSET:
            values["quality"] = quality
        params = StartScreencastParams.model_validate(values)
        await self._rpc.request(
            BROWSER_SCREENCAST_START,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )


class Browser:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc
        self.tabs = BrowserTabs(rpc)
        self.screencast = BrowserScreencast(rpc)
