# Generated by rpckit from automation.openrpc.json.
# Do not edit this file manually.

from collections.abc import AsyncIterator

from automation_client.internal import RpcClientCore
from automation_client.models import (
    CreateTaskParams,
    DeleteTaskParams,
    Task,
    TaskList,
    TaskUpdated,
)
from automation_client.routes import (
    TASKS_CREATE,
    TASKS_DELETE,
    TASKS_LIST,
    TASKS_UPDATED,
)


class Tasks:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def list(self) -> TaskList:
        """List all tasks."""
        return await self._rpc.request(
            TASKS_LIST,
        )

    async def create(
        self,
        *,
        title: str,
    ) -> Task:
        """Create a task."""
        params = CreateTaskParams(
            title=title,
        )
        return await self._rpc.request(
            TASKS_CREATE,
            params=params,
        )

    async def delete(
        self,
        *,
        task_id: str,
    ) -> bool:
        """Delete a task once the operator approves it."""
        params = DeleteTaskParams(
            task_id=task_id,
        )
        return await self._rpc.request(
            TASKS_DELETE,
            params=params,
        )

    def updated(self) -> AsyncIterator[TaskUpdated]:
        """Stream task updates."""
        return self._rpc.subscribe(TASKS_UPDATED)
