# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from showcase.client.client import CalculatorClient
from showcase.client.endpoints import Servers, local_url

__all__ = [
    "CalculatorClient",
    "Servers",
    "local_url",
]
