# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from showcase.client.client import CalculatorClient
from showcase.client.models import RpcMethod
from showcase.client.namespaces import CalculatorNamespaceClient

__all__ = [
    "CalculatorClient",
    "CalculatorNamespaceClient",
    "RpcMethod",
]
