# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from collections.abc import AsyncIterator
from typing import Self

from pydantic import TypeAdapter
from pyrpckit.client import RpcClientCore, RpcTransport

from showcase.client.models import CalculationUpdate, CalculatorUpdatedNotification
from showcase.client.namespaces.calculator import CalculatorApi

_NOTIFICATION_MESSAGE_ADAPTER = TypeAdapter(CalculatorUpdatedNotification)


class CalculatorClient:
    def __init__(
        self,
        transport: RpcTransport,
        *,
        close_transport: bool = True,
    ) -> None:
        self._rpc = RpcClientCore(transport, close_transport=close_transport)
        self.calculator = CalculatorApi(self._rpc)

    async def notifications(self) -> AsyncIterator[CalculationUpdate]:
        async for message in self._rpc.notifications():
            notification = _NOTIFICATION_MESSAGE_ADAPTER.validate_python(message)
            yield notification.params

    async def close(self) -> None:
        await self._rpc.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
