# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from typing import Self

from pyrpckit.client import RpcClientCore, RpcTransport

from showcase.client.api.calculator import CalculatorApi


class CalculatorClient:
    def __init__(
        self,
        transport: RpcTransport,
        *,
        close_transport: bool = True,
    ) -> None:
        self._rpc = RpcClientCore(transport, close_transport=close_transport)
        self.calculator = CalculatorApi(self._rpc)

    async def close(self) -> None:
        await self._rpc.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
