# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from pyrpckit.client import RpcServerInfo


class Servers:
    LOCAL = RpcServerInfo(
        name="local",
        url="http://127.0.0.1:8000/rpc",
        summary="",
        description="",
        variables={},
        transport=None,
    )


def local_url() -> str:
    return Servers.LOCAL.resolve()
