# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from typing import ClassVar

from pyrpckit.client import RpcRemoteError


class DivisionByZeroError(RpcRemoteError):
    code: ClassVar[int] = -32001
