# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from pyrpckit.client import RpcContractInfo, RpcRouteInfo

CONTRACT = RpcContractInfo(
    title="Calculator API",
    version="1.0.0",
    protocol_version=1,
)


CALCULATOR_ADD = RpcRouteInfo(
    method="calculator.add",
    summary="",
    tags=("calculator",),
    deprecated=False,
    error_codes=(),
    server_names=(),
)


CALCULATOR_DIVIDE = RpcRouteInfo(
    method="calculator.divide",
    summary="",
    tags=("calculator",),
    deprecated=False,
    error_codes=(-32001,),
    server_names=(),
)
