# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class RpcMethod(StrEnum):
    CALCULATOR_ADD = "calculator.add"
    CALCULATOR_DIVIDE = "calculator.divide"


class RpcModel(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        validate_by_alias=True,
        validate_by_name=True,
        serialize_by_alias=True,
    )


class BinaryOperationParams(RpcModel):
    model_config = ConfigDict(extra="forbid")
    left: float
    right: float
    decimal_places: int | None = Field(None, alias="decimalPlaces")


class CalculationResult(RpcModel):
    model_config = ConfigDict(extra="forbid")
    value: float


BinaryOperationParams.model_rebuild()
CalculationResult.model_rebuild()
