# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class RpcMethod(StrEnum):
    CALCULATOR_ADD = "calculator.add"
    CALCULATOR_DIVIDE = "calculator.divide"


class BinaryOperationParams(BaseModel):
    left: float
    right: float


class CalculationResult(BaseModel):
    value: float


BinaryOperationParams.model_rebuild()
CalculationResult.model_rebuild()
