# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class RpcModel(BaseModel):
    model_config = ConfigDict(validate_by_name=True)


class BinaryOperationParams(RpcModel):
    model_config = ConfigDict(extra="forbid")
    left: float
    right: float
    decimal_places: int | None = Field(None, alias="decimalPlaces")


class CalculationCompleted(RpcModel):
    model_config = ConfigDict(extra="forbid")
    type: Literal["calculation.completed"] = "calculation.completed"
    operation: Literal["add"] | Literal["divide"]
    result: CalculationResult


class CalculationResult(RpcModel):
    model_config = ConfigDict(extra="forbid")
    value: float


class CalculationStarted(RpcModel):
    model_config = ConfigDict(extra="forbid")
    type: Literal["calculation.started"] = "calculation.started"
    operation: Literal["add"] | Literal["divide"]


class CalculatorUpdatedNotification(RpcModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal["2.0"]
    method: Literal["calculator.updated"]
    params: CalculationUpdate


type CalculationUpdate = CalculationStarted | CalculationCompleted


BinaryOperationParams.model_rebuild()
CalculationCompleted.model_rebuild()
CalculationResult.model_rebuild()
CalculationStarted.model_rebuild()
CalculatorUpdatedNotification.model_rebuild()
