# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from pyrpckit.client import RpcTransport

from showcase.client.models import BinaryOperationParams, CalculationResult, RpcMethod


class CalculatorNamespaceClient:
    def __init__(self, transport: RpcTransport) -> None:
        self._transport = transport

    async def add(
        self,
        *,
        left: float,
        right: float,
        decimal_places: int | None = None,
    ) -> CalculationResult:
        params = BinaryOperationParams(
            left=left,
            right=right,
            decimal_places=decimal_places,
        )
        result = await self._transport.request(
            RpcMethod.CALCULATOR_ADD,
            params.model_dump(mode="json", by_alias=True, exclude_none=True),
        )
        return CalculationResult.model_validate(result)

    async def divide(
        self,
        *,
        left: float,
        right: float,
        decimal_places: int | None = None,
    ) -> CalculationResult:
        params = BinaryOperationParams(
            left=left,
            right=right,
            decimal_places=decimal_places,
        )
        result = await self._transport.request(
            RpcMethod.CALCULATOR_DIVIDE,
            params.model_dump(mode="json", by_alias=True, exclude_none=True),
        )
        return CalculationResult.model_validate(result)
