// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import { RpcClientCore, type RpcTransport } from "./core";
import { resolveEndpoints, type Endpoint, type ServerName } from "./endpoints";
import { WebSocketTransport, type WebSocketFactory } from "./transport";
import { Tasks, Browser } from "./namespaces";

export type AutomationTransports = {
  readonly production: RpcTransport;
  readonly browser: RpcTransport;
  readonly streaming: RpcTransport;
};

export type ConnectOptions = {
  readonly endpoints?: readonly Endpoint[];
  readonly requestTimeoutMs?: number;
  readonly notificationQueueSize?: number;
  readonly socketFactory?: WebSocketFactory;
};

export class AutomationClient {
  readonly tasks: Tasks;
  readonly browser: Browser;

  readonly #rpc: RpcClientCore;

  constructor(
    transport: RpcTransport | AutomationTransports,
    options?: { readonly closeTransport?: boolean },
  ) {
    this.#rpc = new RpcClientCore(transport, options);
    this.tasks = new Tasks(this.#rpc);
    this.browser = new Browser(this.#rpc);
  }

  static fromTransport(transport: RpcTransport): AutomationClient {
    return new AutomationClient(transport);
  }

  static fromTransports(transports: AutomationTransports): AutomationClient {
    return new AutomationClient(transports);
  }

  static async connect(
    options: ConnectOptions = {},
  ): Promise<AutomationClient> {
    const transports: Partial<Record<ServerName, RpcTransport>> = {};
    try {
      for (const endpoint of resolveEndpoints(options.endpoints ?? [])) {
        transports[endpoint.server] = await WebSocketTransport.open(
          endpoint.url,
          {
            subprotocols: endpoint.subprotocols,
            requestTimeoutMs: options.requestTimeoutMs,
            notificationQueueSize: options.notificationQueueSize,
            socketFactory: options.socketFactory,
          },
        );
      }
    } catch (error) {
      await Promise.all(
        Object.values(transports).map((transport) => transport.close()),
      );
      throw error;
    }
    return AutomationClient.fromTransports(transports as AutomationTransports);
  }

  close(): Promise<void> {
    return this.#rpc.close();
  }
}
