// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import {
  RpcClientCore,
  RpcTransportPool,
  type RpcClientHook,
  type RpcTransport,
  type RpcTransportSource,
} from "./core";
import {
  BinaryWebSocketStream,
  type BinaryStreamOpener,
  type BinaryWebSocketFactory,
} from "./streams";
import {
  resolveEndpoints,
  type EndpointOverrides,
  type Endpoint,
  type ServerName,
} from "./endpoints";
import { WebSocketTransport, type WebSocketFactory } from "./transport";
import { Tasks, Browser } from "./namespaces";

export type AutomationTransports = {
  readonly production: RpcTransport;
  readonly browser: RpcTransport;
  readonly streaming: RpcTransport;
};

export type ConnectOptions = {
  readonly host?: string;
  readonly servers?: EndpointOverrides;
  readonly eager?: boolean;
  readonly requestTimeoutMs?: number;
  readonly notificationQueueSize?: number;
  readonly socketFactory?: WebSocketFactory;
  readonly streamSocketFactory?: BinaryWebSocketFactory;
  readonly streamQueueSize?: number;
  readonly hooks?: readonly RpcClientHook[];
};

export class AutomationClient {
  readonly tasks: Tasks;
  readonly browser: Browser;

  readonly #rpc: RpcClientCore;

  constructor(
    transport: RpcTransport | AutomationTransports | RpcTransportSource,
    options?: {
      readonly closeTransport?: boolean;
      readonly hooks?: readonly RpcClientHook[];
      readonly streamOpener?: BinaryStreamOpener;
      readonly variables?: Readonly<Record<string, string>>;
    },
  ) {
    this.#rpc = new RpcClientCore(transport, options);
    this.tasks = new Tasks(this.#rpc);
    this.browser = new Browser(this.#rpc);
  }

  /** Build a client on transports the caller owns, for tests and adapters. */
  static withTransports(
    transports: RpcTransport | AutomationTransports,
    options?: {
      readonly closeTransport?: boolean;
      readonly hooks?: readonly RpcClientHook[];
      readonly streamOpener?: BinaryStreamOpener;
    },
  ): AutomationClient {
    return new AutomationClient(transports, options);
  }

  /** Connect to every declared server, opening each socket on first use. */
  static async connect(
    options: ConnectOptions = {},
  ): Promise<AutomationClient> {
    const variables: Record<string, string | undefined> = {
      host: options.host,
    };
    const pool = new RpcTransportPool({
      endpoints: [...resolveEndpoints(variables, options.servers)],
      open: (endpoint) =>
        WebSocketTransport.open(endpoint.url, {
          subprotocols: endpoint.subprotocols,
          requestTimeoutMs: options.requestTimeoutMs,
          notificationQueueSize: options.notificationQueueSize,
          socketFactory: options.socketFactory,
        }),
    });
    if (options.eager === true) await pool.openAll();
    return new AutomationClient(pool, {
      hooks: options.hooks,
      streamOpener: (endpoint) =>
        BinaryWebSocketStream.open(endpoint, {
          socketFactory: options.streamSocketFactory,
          incomingQueueSize: options.streamQueueSize,
        }),
      variables: definedVariables(variables),
    });
  }

  close(): Promise<void> {
    return this.#rpc.close();
  }

  [Symbol.asyncDispose](): Promise<void> {
    return this.close();
  }
}

function definedVariables(
  values: Readonly<Record<string, string | undefined>>,
): Readonly<Record<string, string>> {
  return Object.fromEntries(
    Object.entries(values).filter(([, value]) => value !== undefined),
  ) as Record<string, string>;
}
