// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcTransport } from "./transport";

export type { RpcTransport } from "./transport";

export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type RpcRouteInfo = {
  readonly method: string;
  readonly server?: string;
};

type JsonRpcNotification = {
  readonly method: string;
  readonly params?: unknown;
};

type Subscriber = {
  readonly method: string;
  readonly queue: AsyncQueue<JsonRpcNotification>;
};

export class RpcRemoteError extends Error {
  constructor(
    readonly code: number,
    message: string,
    readonly data?: unknown,
  ) {
    super(message);
    this.name = "RpcRemoteError";
  }
}

export class RpcClientCore {
  readonly #singleTransport?: RpcTransport;
  readonly #transports?: Readonly<Record<string, RpcTransport>>;
  readonly #closeTransport: boolean;
  readonly #subscribers = new WeakMap<RpcTransport, Set<Subscriber>>();
  readonly #pumps = new WeakSet<RpcTransport>();
  #closed = false;

  constructor(
    transport: RpcTransport | Readonly<Record<string, RpcTransport>>,
    options?: { readonly closeTransport?: boolean },
  ) {
    if (isTransport(transport)) this.#singleTransport = transport;
    else this.#transports = transport;
    this.#closeTransport = options?.closeTransport ?? true;
  }

  request<Result>(route: RpcRouteInfo, params?: object): Promise<Result> {
    return this.#transportFor(route.server).request(
      route.method,
      params === undefined ? undefined : withoutUndefined(params),
    ) as Promise<Result>;
  }

  notifications<Notification>(
    method: string,
    server?: string,
  ): AsyncIterable<Notification> {
    const transport = this.#transportFor(server);
    const subscriber: Subscriber = {
      method,
      queue: new AsyncQueue<JsonRpcNotification>(),
    };
    let subscribers = this.#subscribers.get(transport);
    if (subscribers === undefined) {
      subscribers = new Set();
      this.#subscribers.set(transport, subscribers);
    }
    subscribers.add(subscriber);
    if (!this.#pumps.has(transport)) {
      this.#pumps.add(transport);
      void this.#pump(transport, subscribers);
    }
    return this.#notificationValues<Notification>(subscriber, subscribers);
  }

  async close(): Promise<void> {
    if (this.#closed) return;
    this.#closed = true;
    if (!this.#closeTransport) return;
    const transports = this.#singleTransport
      ? [this.#singleTransport]
      : [...new Set(Object.values(this.#transports ?? {}))];
    await Promise.all(transports.map((transport) => transport.close()));
  }

  async *#notificationValues<Notification>(
    subscriber: Subscriber,
    subscribers: Set<Subscriber>,
  ): AsyncIterable<Notification> {
    try {
      for await (const message of subscriber.queue) {
        yield message.params as Notification;
      }
    } finally {
      subscribers.delete(subscriber);
    }
  }

  async #pump(
    transport: RpcTransport,
    subscribers: Set<Subscriber>,
  ): Promise<void> {
    try {
      for await (const message of transport.notifications()) {
        if (!isNotification(message)) {
          throw new Error(
            "The transport returned an invalid JSON-RPC notification",
          );
        }
        for (const subscriber of subscribers) {
          if (subscriber.method === message.method)
            subscriber.queue.push(message);
        }
      }
      for (const subscriber of subscribers) subscriber.queue.end();
    } catch (error) {
      for (const subscriber of subscribers) subscriber.queue.fail(error);
    }
  }

  #transportFor(server?: string): RpcTransport {
    if (this.#closed) throw new Error("The RPC client is closed");
    if (this.#singleTransport !== undefined) return this.#singleTransport;
    if (server !== undefined) {
      const transport = this.#transports?.[server];
      if (transport !== undefined) return transport;
      throw new Error(`No transport is configured for server ${server}`);
    }
    const transports = Object.values(this.#transports ?? {});
    if (transports.length === 1) return transports[0];
    throw new Error(
      "The route has no server and cannot be dispatched across multiple transports",
    );
  }
}

class AsyncQueue<Value> implements AsyncIterableIterator<Value> {
  readonly #values: Value[] = [];
  readonly #waiters: Array<{
    readonly resolve: (result: IteratorResult<Value>) => void;
    readonly reject: (error: unknown) => void;
  }> = [];
  #ended = false;

  [Symbol.asyncIterator](): AsyncIterableIterator<Value> {
    return this;
  }

  next(): Promise<IteratorResult<Value>> {
    const value = this.#values.shift();
    if (value !== undefined) return Promise.resolve({ value, done: false });
    if (this.#ended) return Promise.resolve({ value: undefined, done: true });
    return new Promise((resolve, reject) => {
      this.#waiters.push({ resolve, reject });
    });
  }

  push(value: Value): void {
    const waiter = this.#waiters.shift();
    if (waiter !== undefined) waiter.resolve({ value, done: false });
    else this.#values.push(value);
  }

  end(): void {
    this.#ended = true;
    for (const waiter of this.#waiters.splice(0)) {
      waiter.resolve({ value: undefined, done: true });
    }
  }

  fail(error: unknown): void {
    this.#ended = true;
    for (const waiter of this.#waiters.splice(0)) waiter.reject(error);
  }
}

function isTransport(value: unknown): value is RpcTransport {
  return (
    typeof value === "object" &&
    value !== null &&
    "request" in value &&
    typeof value.request === "function"
  );
}

function isNotification(value: unknown): value is JsonRpcNotification {
  return (
    typeof value === "object" &&
    value !== null &&
    "method" in value &&
    typeof value.method === "string"
  );
}

function withoutUndefined(value: object): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => [key, normalizeValue(item)]),
  );
}

function normalizeValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value !== null && typeof value === "object")
    return withoutUndefined(value);
  return value;
}
