// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcTransport } from "./transport";
import {
  BinaryStreamConnection,
  RpcStreamsUnavailableError,
  type BinaryStreamEndpoint,
  type BinaryStreamOpener,
} from "./streams";

export type { RpcTransport } from "./transport";

export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type RpcRouteInfo = {
  readonly method: string;
  readonly server?: string;
};

export type RpcClientHook = {
  beforeRequest?(route: RpcRouteInfo, params?: object): void | Promise<void>;
  afterResponse?(route: RpcRouteInfo, result: unknown): void | Promise<void>;
};

type JsonRpcNotification = {
  readonly method: string;
  readonly params?: unknown;
};

type Subscriber = {
  readonly method: string;
  readonly queue: AsyncQueue<JsonRpcNotification>;
};

/**
 * The single notification pump of one transport and its subscribers.
 *
 * `ended` remembers how the pump finished so that a subscriber which arrives
 * afterwards ends or fails immediately instead of waiting forever.
 */
type NotificationHub = {
  readonly subscribers: Set<Subscriber>;
  pumping: boolean;
  ended?: { readonly error?: unknown };
};

export class RpcRemoteError extends Error {
  constructor(
    readonly rpcCode: number,
    readonly code: string,
    message: string,
    readonly details?: unknown,
  ) {
    super(message);
    this.name = "RpcRemoteError";
  }
}

export class RpcConnectionClosed extends Error {
  constructor(
    readonly code: number | undefined,
    readonly reason: string,
  ) {
    super(`RPC connection closed (${code}): ${reason}`);
    this.name = "RpcConnectionClosed";
  }
}

export class RpcClientCore {
  readonly #singleTransport?: RpcTransport;
  readonly #transports?: Readonly<Record<string, RpcTransport>>;
  readonly #closeTransport: boolean;
  readonly streamOpener?: BinaryStreamOpener;

  readonly #hooks: readonly RpcClientHook[];
  readonly #hubs = new WeakMap<RpcTransport, NotificationHub>();
  #closed = false;

  constructor(
    transport: RpcTransport | Readonly<Record<string, RpcTransport>>,
    options?: {
      readonly closeTransport?: boolean;
      readonly hooks?: readonly RpcClientHook[];
      readonly streamOpener?: BinaryStreamOpener;
    },
  ) {
    if (isTransport(transport)) this.#singleTransport = transport;
    else this.#transports = transport;
    this.#closeTransport = options?.closeTransport ?? true;
    this.#hooks = options?.hooks ?? [];
    this.streamOpener = options?.streamOpener;
  }

  async openStream(
    endpoint: BinaryStreamEndpoint,
  ): Promise<BinaryStreamConnection> {
    if (this.streamOpener === undefined) {
      throw new RpcStreamsUnavailableError(
        "No binary stream opener configured; pass streamOpener",
      );
    }
    return new BinaryStreamConnection(await this.streamOpener(endpoint));
  }

  async request<Result>(route: RpcRouteInfo, params?: object): Promise<Result> {
    const payload = params === undefined ? undefined : withoutUndefined(params);
    for (const hook of this.#hooks) await hook.beforeRequest?.(route, payload);
    const result = await this.#transportFor(route.server).request(
      route.method,
      payload,
    );
    for (const hook of [...this.#hooks].reverse()) {
      await hook.afterResponse?.(route, result);
    }
    return result as Result;
  }

  notifications<Notification>(
    route: RpcRouteInfo,
  ): AsyncIterable<Notification> {
    const transport = this.#transportFor(route.server);
    const subscriber: Subscriber = {
      method: route.method,
      queue: new AsyncQueue<JsonRpcNotification>(),
    };
    let hub = this.#hubs.get(transport);
    if (hub === undefined) {
      hub = { subscribers: new Set(), pumping: false };
      this.#hubs.set(transport, hub);
    }
    if (hub.ended !== undefined) {
      if ("error" in hub.ended) subscriber.queue.fail(hub.ended.error);
      else subscriber.queue.end();
    } else {
      hub.subscribers.add(subscriber);
      if (!hub.pumping) {
        hub.pumping = true;
        void this.#pump(transport, hub);
      }
    }
    return this.#notificationValues<Notification>(subscriber, hub);
  }

  async close(): Promise<void> {
    if (this.#closed) return;
    this.#closed = true;
    if (!this.#closeTransport) return;
    const transports = this.#singleTransport
      ? [this.#singleTransport]
      : [...new Set(Object.values(this.#transports ?? {}))];
    await Promise.all(transports.map((transport) => transport.close()));
  }

  async *#notificationValues<Notification>(
    subscriber: Subscriber,
    hub: NotificationHub,
  ): AsyncIterable<Notification> {
    try {
      for await (const message of subscriber.queue) {
        yield message.params as Notification;
      }
    } finally {
      hub.subscribers.delete(subscriber);
    }
  }

  async #pump(transport: RpcTransport, hub: NotificationHub): Promise<void> {
    try {
      for await (const message of transport.notifications()) {
        if (!isNotification(message)) {
          throw new Error(
            "The transport returned an invalid JSON-RPC notification",
          );
        }
        for (const subscriber of hub.subscribers) {
          if (subscriber.method === message.method)
            subscriber.queue.push(message);
        }
      }
      hub.ended = {};
      for (const subscriber of hub.subscribers) subscriber.queue.end();
    } catch (error) {
      hub.ended = { error };
      for (const subscriber of hub.subscribers) subscriber.queue.fail(error);
    }
  }

  #transportFor(server?: string): RpcTransport {
    if (this.#closed) throw new Error("The RPC client is closed");
    if (this.#singleTransport !== undefined) return this.#singleTransport;
    if (server !== undefined) {
      const transport = this.#transports?.[server];
      if (transport !== undefined) return transport;
      throw new Error(`No transport is configured for server ${server}`);
    }
    const transports = Object.values(this.#transports ?? {});
    if (transports.length === 1) return transports[0];
    throw new Error(
      "The route has no server and cannot be dispatched across multiple transports",
    );
  }
}

class AsyncQueue<Value> implements AsyncIterableIterator<Value> {
  readonly #values: Value[] = [];
  readonly #waiters: Array<{
    readonly resolve: (result: IteratorResult<Value>) => void;
    readonly reject: (error: unknown) => void;
  }> = [];
  #ended = false;

  [Symbol.asyncIterator](): AsyncIterableIterator<Value> {
    return this;
  }

  next(): Promise<IteratorResult<Value>> {
    const value = this.#values.shift();
    if (value !== undefined) return Promise.resolve({ value, done: false });
    if (this.#ended) return Promise.resolve({ value: undefined, done: true });
    return new Promise((resolve, reject) => {
      this.#waiters.push({ resolve, reject });
    });
  }

  push(value: Value): void {
    const waiter = this.#waiters.shift();
    if (waiter !== undefined) waiter.resolve({ value, done: false });
    else this.#values.push(value);
  }

  end(): void {
    this.#ended = true;
    for (const waiter of this.#waiters.splice(0)) {
      waiter.resolve({ value: undefined, done: true });
    }
  }

  fail(error: unknown): void {
    this.#ended = true;
    for (const waiter of this.#waiters.splice(0)) waiter.reject(error);
  }
}

function isTransport(value: unknown): value is RpcTransport {
  return (
    typeof value === "object" &&
    value !== null &&
    "request" in value &&
    typeof value.request === "function"
  );
}

function isNotification(value: unknown): value is JsonRpcNotification {
  return (
    typeof value === "object" &&
    value !== null &&
    "method" in value &&
    typeof value.method === "string"
  );
}

function withoutUndefined(value: object): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => [key, normalizeValue(item)]),
  );
}

function normalizeValue(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value !== null && typeof value === "object")
    return withoutUndefined(value);
  return value;
}
