// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export type RpcTransportDescriptor =
  | {
      readonly type: "websocket";
      readonly messageEncoding: "json";
      readonly subprotocols?: readonly string[];
    }
  | {
      readonly type: string;
      readonly subprotocols?: readonly string[];
      readonly [option: string]: unknown;
    };

type RpcServerVariable = {
  readonly default: string;
  readonly description?: string;
  readonly enum?: readonly string[];
};

type RpcServerInfo = {
  readonly name: string;
  readonly url: string;
  readonly summary?: string;
  readonly description?: string;
  readonly variables?: Readonly<Record<string, RpcServerVariable>>;
  readonly transport?: RpcTransportDescriptor;
};

export type ServerName = "production" | "browser" | "streaming";

export type Endpoint = {
  readonly server: ServerName;
  readonly url: string | URL;
  readonly subprotocols?: readonly string[];
};

export type ServerVariables = Readonly<Record<string, string | undefined>>;

export type EndpointOverrides = Partial<
  Record<ServerName, string | URL | Endpoint>
>;

const serverNames: readonly ServerName[] = [
  "production",
  "browser",
  "streaming",
];

export const servers = {
  production: {
    name: "production",
    url: "wss://{host}/automation/rpc",
    transport: {
      type: "websocket",
      messageEncoding: "json",
      frameType: "text",
    },
    variables: {
      host: {
        default: "api.example.com",
      },
    },
  },
  browser: {
    name: "browser",
    url: "wss://{host}/browser/rpc",
    transport: {
      type: "websocket",
      messageEncoding: "json",
      frameType: "text",
    },
    variables: {
      host: {
        default: "api.example.com",
      },
    },
  },
  streaming: {
    name: "streaming",
    url: "wss://{host}/browser/stream",
    transport: {
      type: "websocket",
      messageEncoding: "json",
      subprotocols: ["pyrpckit.jsonrpc"],
      frameType: "text",
    },
    variables: {
      host: {
        default: "api.example.com",
      },
    },
  },
} as const satisfies Record<string, RpcServerInfo>;

function production(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return endpoint("production", variables);
}

function browser(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return endpoint("browser", variables);
}

function streaming(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return endpoint("streaming", variables);
}

export const endpoints = {
  production,
  browser,
  streaming,
} as const;

/** Resolve one declared server, ignoring variables it does not declare. */
export function endpoint(
  server: ServerName,
  variables: ServerVariables = {},
): Endpoint {
  const info: RpcServerInfo = servers[server];
  return {
    server,
    url: resolveUrl(info, variables),
    subprotocols: info.transport?.subprotocols ?? [],
  };
}

/** Resolve every declared server, then apply the caller's overrides. */
export function resolveEndpoints(
  variables: ServerVariables = {},
  overrides: EndpointOverrides = {},
): readonly Endpoint[] {
  const resolved = new Map<ServerName, Endpoint>(
    serverNames.map((name) => [name, endpoint(name, variables)]),
  );
  for (const [name, override] of Object.entries(overrides)) {
    const server = name as ServerName;
    const declared = resolved.get(server);
    if (declared === undefined) throw new Error(`Unknown server ${name}`);
    if (override === undefined) continue;
    if (
      typeof override !== "string" &&
      !(override instanceof URL) &&
      override.server !== server
    ) {
      throw new Error(
        `Endpoint override for ${server} declares ${override.server}`,
      );
    }
    resolved.set(
      server,
      typeof override === "string" || override instanceof URL
        ? { ...declared, url: websocketUrl(override) }
        : {
            ...override,
            subprotocols: override.subprotocols ?? declared.subprotocols,
          },
    );
  }
  return [...resolved.values()];
}

function websocketUrl(value: string | URL): string {
  const url = String(value);
  if (url.startsWith("https://")) return `wss://${url.slice(8)}`;
  if (url.startsWith("http://")) return `ws://${url.slice(7)}`;
  return url;
}

function resolveUrl(server: RpcServerInfo, values: ServerVariables): string {
  let url = server.url;
  for (const [name, variable] of Object.entries(server.variables ?? {})) {
    const value = values[name] ?? variable.default;
    if (variable.enum !== undefined && !variable.enum.includes(value)) {
      throw new Error(`Invalid value for server variable ${name}: ${value}`);
    }
    url = url.replaceAll(`{${name}}`, value);
  }
  return url;
}
