// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export type RpcTransportDescriptor =
  | {
      readonly type: "websocket";
      readonly messageEncoding: "json";
      readonly subprotocols?: readonly string[];
    }
  | {
      readonly type: string;
      readonly [option: string]: unknown;
    };

type RpcServerVariable = {
  readonly default: string;
  readonly description?: string;
  readonly enum?: readonly string[];
};

type RpcServerInfo = {
  readonly name: string;
  readonly url: string;
  readonly summary?: string;
  readonly description?: string;
  readonly variables?: Readonly<Record<string, RpcServerVariable>>;
  readonly transport?: RpcTransportDescriptor;
};

export type ServerName = "production" | "browser" | "streaming";

export type Endpoint = {
  readonly server: ServerName;
  readonly url: string | URL;
  readonly subprotocols?: readonly string[];
};

export const servers = {
  production: {
    name: "production",
    url: "wss://{host}/automation/rpc",
    transport: {
      type: "websocket",
      messageEncoding: "json",
    },
    variables: {
      host: {
        default: "api.example.com",
      },
    },
  },
  browser: {
    name: "browser",
    url: "wss://{host}/browser/rpc",
    transport: {
      type: "websocket",
      messageEncoding: "json",
    },
    variables: {
      host: {
        default: "browser.example.com",
      },
    },
  },
  streaming: {
    name: "streaming",
    url: "wss://{host}/browser/stream",
    transport: {
      type: "websocket",
      messageEncoding: "json",
      subprotocols: ["pyrpckit.jsonrpc"],
    },
    variables: {
      host: {
        default: "stream.example.com",
      },
    },
  },
} as const satisfies Record<string, RpcServerInfo>;

function production(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return {
    server: "production",
    url: resolveUrl(servers.production, variables),
    subprotocols: [],
  };
}

function browser(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return {
    server: "browser",
    url: resolveUrl(servers.browser, variables),
    subprotocols: [],
  };
}

function streaming(
  variables: {
    host?: string;
  } = {},
): Endpoint {
  return {
    server: "streaming",
    url: resolveUrl(servers.streaming, variables),
    subprotocols: ["pyrpckit.jsonrpc"],
  };
}

export const endpoints = {
  production,
  browser,
  streaming,
} as const;

export function resolveEndpoints(
  overrides: readonly Endpoint[],
): readonly Endpoint[] {
  const resolved = new Map<ServerName, Endpoint>([
    ["production", production()],
    ["browser", browser()],
    ["streaming", streaming()],
  ]);
  const supplied = new Set<ServerName>();
  for (const endpoint of overrides) {
    if (supplied.has(endpoint.server)) {
      throw new Error(`Duplicate endpoint for ${endpoint.server}`);
    }
    supplied.add(endpoint.server);
    const declared = resolved.get(endpoint.server);
    resolved.set(endpoint.server, {
      ...endpoint,
      subprotocols: endpoint.subprotocols ?? declared?.subprotocols,
    });
  }
  return [...resolved.values()];
}

function resolveUrl(
  server: RpcServerInfo,
  values: Readonly<Record<string, string>>,
): string {
  let url = server.url;
  for (const [name, variable] of Object.entries(server.variables ?? {})) {
    const value = values[name] ?? variable.default;
    if (variable.enum !== undefined && !variable.enum.includes(value)) {
      throw new Error(`Invalid value for server variable ${name}: ${value}`);
    }
    url = url.replaceAll(`{${name}}`, value);
  }
  return url;
}
