// Generated by rpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import { RpcRemoteError } from "./core";

const errorTypes: Readonly<Record<string, typeof RpcRemoteError>> = {};

export function errorFromResponse(
  rpcCode: number,
  code: string,
  message: string,
  details?: unknown,
): RpcRemoteError {
  const ErrorType = errorTypes[code] ?? RpcRemoteError;
  return new ErrorType(rpcCode, code, message, details);
}
