// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export { AutomationClient } from "./client";
export * from "./namespaces";
export { RpcConnectionClosed, RpcRemoteError } from "./core";
export type {
  JsonValue,
  RpcClientCore,
  RpcClientHook,
  RpcRouteInfo,
  RpcTransport,
} from "./core";
export * from "./errors";
export { routes, notifications } from "./routes";
export { endpoints, servers } from "./endpoints";
export type { Endpoint, ServerName } from "./endpoints";
export { WebSocketTransport } from "./transport";
export type { WebSocketFactory, WebSocketOptions } from "./transport";
export {
  BinaryDuplexConnection,
  BinarySinkConnection,
  BinaryStreamConnection,
  RpcStreamClosed,
  RpcStreamFailed,
  RpcStreamRefused,
  RpcStreamsUnavailableError,
  binaryStreams,
  resolveStreamEndpoint,
} from "./streams";
export type {
  BinaryInputTransport,
  BinaryStreamDirection,
  BinaryStreamEndpoint,
  BinaryStreamName,
  BinaryStreamTransport,
} from "./streams";
export { BinaryWebSocketStream } from "./streams";
export type { BinaryWebSocketFactory, BinaryWebSocketOptions } from "./streams";
export type * from "./models";
