// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export type Task = {
  id: string;
  title: string;
  status: "open" | "done";
};

export type CreateTaskParams = {
  title: string;
};

export type Tab = {
  id: string;
  url: string;
};

export type OpenTabParams = {
  url: string;
};

export type StartScreencastParams = {
  quality?: number;
};

export type TaskUpdated = {
  task: Task;
};

export type TaskUpdatedNotification = {
  jsonrpc: "2.0";
  method: "tasks.updated";
  params: TaskUpdated;
};

export type Frame = {
  sequence: number;
  data: string;
};

export type FrameNotification = {
  jsonrpc: "2.0";
  method: "browser.screencast.frames";
  params: Frame;
};

export type TaskList = Task[];
