// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export type ApprovalDecision = {
  approved: boolean;
  comment?: string | null;
};

export type ApprovalRequest = {
  taskId: string;
  action: string;
};

export type CreateTaskParams = {
  title: string;
};

export type DeleteTaskParams = {
  taskId: string;
};

export type DialogAnswer = {
  accepted: boolean;
};

export type DialogRequest = {
  tabId: string;
  message: string;
};

export type OpenTabParams = {
  url: string;
};

export type StartScreencastParams = {
  quality?: number;
};

export type Tab = {
  id: string;
  url: string;
};

export type Task = {
  id: string;
  title: string;
  done?: boolean;
};

export type TaskList = {
  tasks: Task[];
};

export type TaskUpdated = {
  task: Task;
};

export type TasksUpdatedNotification = {
  jsonrpc: "2.0";
  method: "tasks.updated";
  params: TaskUpdated;
};
