// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcRouteInfo } from "./core";

export const routes = {
  tasksList: {
    method: "tasks.list",
    server: "production",
  },
  tasksCreate: {
    method: "tasks.create",
    server: "production",
  },
  browserTabsOpen: {
    method: "browser.tabs.open",
    server: "browser",
  },
  browserScreencastStart: {
    method: "browser.screencast.start",
    server: "streaming",
  },
} as const satisfies Record<string, RpcRouteInfo>;
