// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import { defineNotification, defineRoute } from "./core";
import type {
  CreateTaskParams,
  OpenTabParams,
  StartScreencastParams,
  Tab,
  Task,
  TaskList,
  TaskUpdated,
} from "./models";

export const routes = {
  tasksList: defineRoute<undefined, TaskList>({
    method: "tasks.list",
    server: "production",
  }),
  tasksCreate: defineRoute<CreateTaskParams, Task>({
    method: "tasks.create",
    server: "production",
  }),
  browserTabsOpen: defineRoute<OpenTabParams, Tab>({
    method: "browser.tabs.open",
    server: "browser",
  }),
  browserScreencastStart: defineRoute<StartScreencastParams, null>({
    method: "browser.screencast.start",
    server: "streaming",
  }),
} as const;

export const notifications = {
  tasksUpdated: defineNotification<TaskUpdated>({
    method: "tasks.updated",
    server: "production",
  }),
} as const;
