// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

export type BinaryStreamDirection = "server-to-client";

export type BinaryStreamName = "browser.screencast.frames";

export type BinaryStreamEndpoint = {
  readonly name: BinaryStreamName;
  readonly url: string | URL;
  readonly direction: BinaryStreamDirection;
  readonly contentType: string;
  readonly subprotocols?: readonly string[];
};

export type BinaryStreamTransport = {
  receive(): Promise<ArrayBuffer>;
  close(): Promise<void>;
};

export type BinaryStreamOpener = (
  endpoint: BinaryStreamEndpoint,
) => Promise<BinaryStreamTransport>;

export class RpcStreamsUnavailableError extends Error {}

/** Raised when a binary stream ended because the server closed it. */
export class RpcStreamClosed extends Error {}

export class BinaryStreamConnection implements AsyncIterable<ArrayBuffer> {
  constructor(private readonly transport: BinaryStreamTransport) {}

  receive(): Promise<ArrayBuffer> {
    return this.transport.receive();
  }

  async *[Symbol.asyncIterator](): AsyncIterator<ArrayBuffer> {
    try {
      while (true) yield await this.receive();
    } catch (error) {
      if (!(error instanceof RpcStreamClosed)) throw error;
    }
  }

  close(): Promise<void> {
    return this.transport.close();
  }

  [Symbol.asyncDispose](): Promise<void> {
    return this.close();
  }
}

export type BinaryStreamInfo = {
  readonly name: BinaryStreamName;
  readonly url: string;
  readonly direction: BinaryStreamDirection;
  readonly contentType: string;
  readonly subprotocols?: readonly string[];
  readonly variables?: Readonly<
    Record<
      string,
      {
        readonly default: string;
        readonly enum?: readonly string[];
      }
    >
  >;
};

export const binaryStreams = {
  browserScreencastFrames: {
    name: "browser.screencast.frames",
    url: "wss://{host}/browser/screencast",
    direction: "server-to-client",
    contentType: "image/jpeg",
    subprotocols: ["pyrpckit.binary"],
    variables: {
      host: {
        default: "stream.example.com",
      },
    },
  },
} as const satisfies Record<string, BinaryStreamInfo>;

export type StreamVariables = Readonly<Record<string, string | undefined>>;

/** Fill a stream URL, falling back to the values the client connected with. */
export function resolveStreamEndpoint(
  stream: BinaryStreamInfo,
  values: StreamVariables = {},
  options: {
    readonly url?: string | URL;
    readonly defaults?: StreamVariables;
  } = {},
): BinaryStreamEndpoint {
  return {
    name: stream.name,
    url: resolveUrl(stream, values, options),
    direction: stream.direction,
    contentType: stream.contentType,
    subprotocols: stream.subprotocols,
  };
}

function resolveUrl(
  stream: BinaryStreamInfo,
  values: StreamVariables,
  options: { readonly url?: string | URL; readonly defaults?: StreamVariables },
): string {
  let url = String(options.url ?? stream.url);
  for (const [name, variable] of Object.entries(stream.variables ?? {})) {
    const value = values[name] ?? options.defaults?.[name] ?? variable.default;
    if (variable.enum !== undefined && !variable.enum.includes(value)) {
      throw new Error(
        `Invalid value for binary stream variable ${name}: ${value}`,
      );
    }
    url = url.replaceAll(`{${name}}`, value);
  }
  return url;
}
export type BinaryWebSocketFactory = (
  url: string | URL,
  protocols?: readonly string[],
) => BinaryWebSocket;

export type BinaryWebSocketOptions = {
  readonly incomingQueueSize?: number;
  readonly socketFactory?: BinaryWebSocketFactory;
};

type BinaryWebSocket = {
  binaryType: string;
  readonly readyState: number;
  close(): void;
  addEventListener(
    type: "open" | "close" | "error",
    listener: () => void,
  ): void;
  addEventListener(
    type: "message",
    listener: (event: { readonly data: unknown }) => void,
  ): void;
};

export class BinaryWebSocketStream implements BinaryStreamTransport {
  readonly endpoint: BinaryStreamEndpoint;
  readonly #socket: BinaryWebSocket;
  readonly #frames: BinaryFrameQueue;
  #closed = false;

  private constructor(
    socket: BinaryWebSocket,
    endpoint: BinaryStreamEndpoint,
    incomingQueueSize: number,
  ) {
    this.#socket = socket;
    this.endpoint = endpoint;
    this.#frames = new BinaryFrameQueue(incomingQueueSize);
    socket.binaryType = "arraybuffer";
    socket.addEventListener("message", (event) => {
      try {
        if (event.data instanceof ArrayBuffer) this.#frames.push(event.data);
        else throw new Error("The binary WebSocket returned a text frame");
      } catch (error) {
        this.#fail(
          error instanceof Error ? error : new Error("Invalid binary frame"),
        );
        socket.close();
      }
    });
    socket.addEventListener("error", () =>
      this.#fail(new Error("The binary WebSocket connection failed")),
    );
    socket.addEventListener("close", () => this.#end());
  }

  static async open(
    endpoint: BinaryStreamEndpoint,
    options: BinaryWebSocketOptions = {},
  ): Promise<BinaryWebSocketStream> {
    const socketFactory =
      options.socketFactory ?? defaultBinaryWebSocketFactory;
    const incomingQueueSize = options.incomingQueueSize ?? 100;
    if (!Number.isInteger(incomingQueueSize) || incomingQueueSize <= 0) {
      throw new Error("incomingQueueSize must be a positive integer");
    }
    const socket = socketFactory(endpoint.url, endpoint.subprotocols);
    socket.binaryType = "arraybuffer";
    await waitForOpen(socket);
    return new BinaryWebSocketStream(socket, endpoint, incomingQueueSize);
  }

  receive(): Promise<ArrayBuffer> {
    if (this.#closed)
      return Promise.reject(new RpcStreamClosed("The binary stream is closed"));
    return this.#frames.receive();
  }

  async close(): Promise<void> {
    if (this.#closed) return;
    this.#closed = true;
    this.#socket.close();
    this.#end();
  }

  #end(): void {
    this.#closed = true;
    this.#frames.fail(new RpcStreamClosed("The binary stream is closed"));
  }

  #fail(error: Error): void {
    if (this.#closed) return;
    this.#closed = true;
    this.#frames.fail(error);
  }
}

class BinaryFrameQueue {
  readonly #capacity: number;
  readonly #values: ArrayBuffer[] = [];
  readonly #waiters: Array<{
    readonly resolve: (value: ArrayBuffer) => void;
    readonly reject: (error: unknown) => void;
  }> = [];
  #failure?: unknown;

  constructor(capacity: number) {
    this.#capacity = capacity;
  }

  receive(): Promise<ArrayBuffer> {
    const value = this.#values.shift();
    if (value !== undefined) return Promise.resolve(value);
    if (this.#failure !== undefined) return Promise.reject(this.#failure);
    return new Promise((resolve, reject) =>
      this.#waiters.push({ resolve, reject }),
    );
  }

  push(value: ArrayBuffer): void {
    const waiter = this.#waiters.shift();
    if (waiter !== undefined) waiter.resolve(value);
    else {
      if (this.#values.length === this.#capacity) {
        throw new Error("The binary WebSocket frame queue overflowed");
      }
      this.#values.push(value);
    }
  }

  fail(error: unknown): void {
    if (this.#failure !== undefined) return;
    this.#failure = error;
    for (const waiter of this.#waiters.splice(0)) waiter.reject(error);
  }
}

function defaultBinaryWebSocketFactory(
  url: string | URL,
  protocols?: readonly string[],
): BinaryWebSocket {
  const constructor = (
    globalThis as unknown as {
      readonly WebSocket?: new (
        url: string | URL,
        protocols?: readonly string[],
      ) => BinaryWebSocket;
    }
  ).WebSocket;
  if (constructor === undefined) {
    throw new Error(
      "No global WebSocket implementation is available; provide socketFactory",
    );
  }
  return new constructor(url, protocols);
}

function waitForOpen(socket: BinaryWebSocket): Promise<void> {
  if (socket.readyState === 1) return Promise.resolve();
  return new Promise((resolve, reject) => {
    socket.addEventListener("open", resolve);
    socket.addEventListener("error", () =>
      reject(new Error("Binary WebSocket open failed")),
    );
    socket.addEventListener("close", () =>
      reject(new Error("Binary WebSocket closed")),
    );
  });
}
