// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcClientCore } from "../../core";
import { BrowserTabs } from "./tabs";
import { BrowserScreencast } from "./screencast";

export class Browser {
  readonly tabs: BrowserTabs;
  readonly screencast: BrowserScreencast;

  constructor(private readonly rpc: RpcClientCore) {
    this.tabs = new BrowserTabs(rpc);
    this.screencast = new BrowserScreencast(rpc);
  }
}
