// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcClientCore } from "../../core";
import { routes } from "../../routes";
import type { OpenTabParams, Tab } from "../../models";

export class BrowserTabs {
  constructor(private readonly rpc: RpcClientCore) {}

  /** Open a browser tab. */
  open(params: OpenTabParams): Promise<Tab> {
    return this.rpc.request<Tab>(routes.browserTabsOpen, params);
  }
}
