# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from examples.calculator_client.client import CalculatorClient
from examples.calculator_client.models import RpcMethod
from examples.calculator_client.namespaces import CalculatorNamespaceClient

__all__ = [
    "CalculatorClient",
    "CalculatorNamespaceClient",
    "RpcMethod",
]
