# Generated by pyrpckit from calculator.openrpc.json.
# Do not edit this file manually.
from typing import Self

from pyrpckit.client import RpcTransport

from examples.calculator_client.namespaces import CalculatorNamespaceClient


class CalculatorClient:
    def __init__(self, transport: RpcTransport) -> None:
        self._transport = transport
        self.calculator = CalculatorNamespaceClient(transport)

    async def close(self) -> None:
        await self._transport.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *args: object) -> None:
        await self.close()
