// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcClientCore } from "../core";
import { routes } from "../routes";
import type {
  Frame,
  OpenTabParams,
  StartScreencastParams,
  Tab,
} from "../models";

export class BrowserTabs {
  constructor(private readonly rpc: RpcClientCore) {}

  /** Open a browser tab. */
  open(params: OpenTabParams): Promise<Tab> {
    return this.rpc.request<Tab>(routes.browserTabsOpen, params);
  }
}

export class BrowserScreencast {
  constructor(private readonly rpc: RpcClientCore) {}

  /** Start the browser screencast. */
  async start(params: StartScreencastParams = {}): Promise<void> {
    await this.rpc.request<null>(routes.browserScreencastStart, params);
  }

  /** Stream screencast frames. */
  frames(): AsyncIterable<Frame> {
    return this.rpc.notifications<Frame>(
      "browser.screencast.frames",
      "streaming",
    );
  }
}

export class Browser {
  readonly tabs: BrowserTabs;
  readonly screencast: BrowserScreencast;

  constructor(private readonly rpc: RpcClientCore) {
    this.tabs = new BrowserTabs(rpc);
    this.screencast = new BrowserScreencast(rpc);
  }
}
