// Generated by pyrpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcClientCore } from "../core";
import { routes } from "../routes";
import type { CreateTaskParams, Task, TaskList, TaskUpdated } from "../models";

export class Tasks {
  constructor(private readonly rpc: RpcClientCore) {}

  /** List all tasks. */
  list(): Promise<TaskList> {
    return this.rpc.request<TaskList>(routes.tasksList);
  }

  /** Create a task. */
  create(params: CreateTaskParams): Promise<Task> {
    return this.rpc.request<Task>(routes.tasksCreate, params);
  }

  /** Stream task updates. */
  updated(): AsyncIterable<TaskUpdated> {
    return this.rpc.notifications<TaskUpdated>("tasks.updated", "production");
  }
}
