// Generated by rpckit from automation.openrpc.json.
// Do not edit this file manually.
// Regenerate it from the OpenRPC document instead.

import type { RpcClientCore } from "../core";
import { routes, notifications } from "../routes";
import type {
  CreateTaskParams,
  DeleteTaskParams,
  Task,
  TaskList,
  TaskUpdated,
} from "../models";

export class Tasks {
  constructor(private readonly rpc: RpcClientCore) {}

  /** List all tasks. */
  list(): Promise<TaskList> {
    return this.rpc.request(routes.tasksList);
  }

  /** Create a task. */
  create(params: CreateTaskParams): Promise<Task> {
    return this.rpc.request(routes.tasksCreate, params);
  }

  /** Delete a task once the operator approves it. */
  delete_(params: DeleteTaskParams): Promise<boolean> {
    return this.rpc.request(routes.tasksDelete, params);
  }

  /** Stream task updates. */
  updated(): AsyncIterable<TaskUpdated> {
    return this.rpc.notifications(notifications.tasksUpdated);
  }
}
