# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from automation_client.internal import RpcClientCore
from automation_client.namespaces.browser.screencast import BrowserScreencast
from automation_client.namespaces.browser.tabs import BrowserTabs


class Browser:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc
        self.tabs = BrowserTabs(rpc)
        self.screencast = BrowserScreencast(rpc)
