# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from collections.abc import AsyncIterator

from pyrpckit.client import RpcClientCore

from automation_client.models import Frame, StartScreencastParams
from automation_client.routes import BROWSER_SCREENCAST_FRAMES, BROWSER_SCREENCAST_START


class BrowserScreencast:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def start(
        self,
        *,
        quality: int = 80,
    ) -> None:
        """Start the browser screencast."""
        params = StartScreencastParams(
            quality=quality,
        )
        await self._rpc.request(
            BROWSER_SCREENCAST_START,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )

    def frames(self) -> AsyncIterator[Frame]:
        """Stream screencast frames."""
        return self._rpc.subscribe(BROWSER_SCREENCAST_FRAMES)
