# Generated by pyrpckit from automation.openrpc.json.
# Do not edit this file manually.
from pyrpckit.client import RpcClientCore

from automation_client.models import OpenTabParams, Tab
from automation_client.routes import BROWSER_TABS_OPEN


class BrowserTabs:
    def __init__(self, rpc: RpcClientCore) -> None:
        self._rpc = rpc

    async def open(
        self,
        *,
        url: str,
    ) -> Tab:
        """Open a browser tab."""
        params = OpenTabParams(
            url=url,
        )
        return await self._rpc.request(
            BROWSER_TABS_OPEN,
            params=params.model_dump(mode="json", by_alias=True, exclude_unset=True),
        )
